In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import builtins
from google.colab import drive

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
drive.mount('/content/drive')

DRIVE_DATA_PATH = "/content/drive/My Drive/WVS_happiness_study"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!python3 --version

Python 3.12.12

In [6]:
# Added for split notebook reruns: load Data Cleaning output if this notebook is run independently.
from pathlib import Path

if "df_cleaned" not in globals():
    _cleaned_candidates = [
        Path(f"{DRIVE_DATA_PATH}/cleaned_df.csv"),
        Path(f"{DRIVE_DATA_PATH}data/cleaned_df.csv"),
        Path(f"{DRIVE_DATA_PATH}data/cleaned_df.csv.zip"),
        Path(f"{DRIVE_DATA_PATH}/data/processed/cleaned_df.csv"),
        Path(f"{DRIVE_DATA_PATH}/data/processed/cleaned_df.csv.zip")
    ]
    for _path in _cleaned_candidates:
        if _path.exists():
            df_cleaned = pd.read_csv(_path)
            print(f"Loaded df_cleaned from {_path}")
            break
    else:
        raise FileNotFoundError("Could not find cleaned_df.csv. Run the Data Cleaning notebook first.")

Loaded df_cleaned from /content/drive/My Drive/WVS_happiness_study/data/processed/cleaned_df.csv

In [7]:
# Added for split notebook reruns: load questionnaire metadata if needed.
from pathlib import Path

if "variable_table" not in globals():
    _questionnaire_candidates = [
        Path(f"{DRIVE_DATA_PATH}/Questionnaire.xlsx"),
        Path(f"{DRIVE_DATA_PATH}/data/Questionnaire.xlsx"),
        Path(f"{DRIVE_DATA_PATH}/data/raw/Questionnaire.xlsx")
    ]
    for _path in _questionnaire_candidates:
        if _path.exists():
            variable_table = pd.read_excel(_path)
            print(f"Loaded variable_table from {_path}")
            break
    else:
        raise FileNotFoundError("Could not find Questionnaire.xlsx.")

Loaded variable_table from /content/drive/My Drive/WVS_happiness_study/data/raw/Questionnaire.xlsx

In [8]:
def var_description(df, scale_description=False, new_var_name=False):
    for col in df.columns:
        print(col, f'dtype={df[col].dtype}')
        print('Unique values:', df[col].sort_values(ascending=True).unique().tolist())
        if scale_description:

            if new_var_name:
                cond = variable_table['New Variable Name'] == col
            else:
                cond = variable_table['Q_num'] == col
            scale_desc = variable_table[cond]['Q_Scale']

            if not scale_desc.empty:
                # Clean the scale description by replacing \n with spaces
                cleaned_desc = scale_desc.iloc[0].replace('\n', ' ')
                # Optional: Remove extra spaces that might result from the replacement
                cleaned_desc = ' '.join(cleaned_desc.split())
                print('Scale description:', cleaned_desc)
            else:
                print('Scale description: Not found')
        print("-" * 100)

#show and retrieve the missing data percentage by threshold
def get_na_cols_perc(df, threshold):
    na_cols = []
    count = 0
    for col in df.columns:
        na_percentage = df[col].isna().sum()/ len(df)
        if(na_percentage >= threshold):
            print(col, f": {na_percentage}")
            na_cols.append(col)
            count += 1
    print("-"*100)
    print("Total column: ", count)
    return na_cols

### Feature Engineering

#### Import Packages

In [9]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import warnings
import json
from joblib import Parallel, delayed
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer, IterativeImputer
from sklearn.preprocessing import OneHotEncoder, FunctionTransformer, StandardScaler, LabelEncoder
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score

warnings.filterwarnings("ignore")

In [10]:
df_fea_eng = df_cleaned
df_fea_eng.head()

,country,belonging1,belonging2,esteem1,civic1,esteem2,belonging3,trust1,growth1,growth2,civic2,growth3,ethical1,ethical2,growth4,growth5,ethical3,ethical4,ethical5,ethical6,ethical7,ethical8,ethical9,ethical10,ethical11,ethical12,ethical13,esteem3,belonging4,ga_leaders_male_better,ga_edu_male_priority,ga_exec_male_better,esteem4,ga_jobs_male_priority,emp_prior_immig,ga_income_woman_problem,ethical14,civic3,civic4,ethical15,civic5,civic6,society_concern,growth6,growth7,growth8,happy,physio1,esteem5,sact,safety1,physio2,safety2,physio3,safety3,safety4,esteem6,trust2,trust3,trust4,trust5,trust6,trust7,trust8,trust9,trust10,trust11,trust12,trust13,trust14,trust15,trust16,trust17,trust18,trust19,trust20,trust21,trust22,trust23,trust24,trust25,trust26,trust27,trust28,trust29,trust30,trust31,trust32,trust33,trust34,ethical16,UN_country,IMF_head,Amn_Int_org_prob,civic7,civic8,civic9,civic10,civic11,civic12,civic13,civic14,civic15,civic16,civic17,civic18,income_eq_vs_diff,pri_vs_state,gov_vs_individual,comp_good_vs_harm,growth9,protect_env_vs_econ,ethical17,ethical18,ethical19,ethical20,ethical21,ethical22,ethical23,ga_women_less_corrupt,ethical24,compassion1,civic19,compassion2,ethical25,compassion3,ethical26,compassion4,civic20,ethical27,immig_policy_prefer,safety5,safety6,safety7,safety8,safety9,safety10,safety11,safety12,safety13,safety14,safety15,safety16,safety17,safety18,safety19,safety20,safety21,safety22,freedom_eq,freedom_sec,civic21,country_aim1,country_aim2,respon_aim1,respon_aim2,important_choice1,important_choice2,growth10,civic22,ethical28,ethical29,growth11,ethical30,growth12,ethical31,growth13,ethical32,growth14,religious1,ethical33,trust35,growth15,religious2,religious3,religious4,ethical34,ethical35,ethical36,ethical37,ethical38,ethical39,ethical40,ethical41,ethical42,ethical43,ethical44,ethical45,ethical46,ethical47,ethical48,ethical49,ethical50,ethical51,ethical52,ethical53,ethical54,ethical55,ethical56,civic23,civic24,civic25,civic26,civic27,civic28,civic29,civic30,civic31,civic32,civic33,civic34,civic35,civic36,civic37,civic38,civic39,civic40,civic41,civic42,civic43,civic44,civic45,civic46,party_vote,ethical57,ethical58,ethical59,ethical60,ethical61,ethical62,ethical63,ethical64,ethical65,ethical66,civic47,ethical67,ethical68,ethical69,ethical70,civic48,ethical71,l_vs_r_political,ethical72,ethical73,civic49,ethical74,ethical75,ethical76,ethical77,ethical78,ethical79,civic50,civic51,civic52,ethical80,civic53,growth16,growth17,growth18,growth19,growth20,sex,date_of_birth,age,immigrant,mom_immigrant,dad_immigrant,birth_country,mom_birth_country,dad_birth_country,citizenship,num_of_household,live_with_parent,mother_tongue,marital_status,num_of_child,education_level,spouse_education_level,mom_education_level,dad_education_level,employment_status,spouse_employment_status,occupational_group,spouse_occupational_group,dad_occupational_group,Employment_sector,chief_wage,family_saving,social_class,income_scale,religiosity,race
0,CYP,4.0,4.0,4.0,1.0,4.0,4.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,4.0,1.0,2.0,2.0,2.0,1.0,2.0,5.0,4.0,1.0,3.0,5.0,3.0,2.0,3.0,2.0,3.0,1.0,NaN,3.0,2.0,5.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,3.0,1.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,1.0,3.0,1.0,2.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,1.0,1.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,1.0,1.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,2.0,2.0,0.0,1.0,3.0,3.0,4.0,1.0,3.0,3.0,1.0,5.0,5.0,1.0,3.0,5.0,1.0,NaN,NaN,NaN,NaN,3.0,1.0,5.0,1.0,0.0,0.0,1.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,3.0,3.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,4.0,4.0,1.0,1.0,1.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,NaN,1.0,NaN,1.0,2.0,2.0,1.0,2.0,NaN,2.0,3.0,1.0,4.0,4.0,1.0,1.0,4.0,1.0,NaN,5.0,3.0,5.0,5.0,1.0,5.0,5.0,5.0,5.0,5.0,1.0,1.0,1.0,4.0,4.0,4.0,4.0,1.0,1.0,0.0,1958.0,61.0,0.0,0.0,0.0,196.0,196.0,196.0,1.0,2.0,0.0,1580.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,4.0,6.0,0.0,9.0,1.0,1.0,2.0,3.0,3.0,3.0,196001.0
1,CYP,4.0,2.0,4.0,2.0,4.0,4.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,NaN,1.0,1.0,2.0,3.0,5.0,2.0,NaN,NaN,5.0,5.0,5.0,4.0,NaN,3.0,3.0,3.0,4.0,4.0,3.0,4.0,3.0,4.0,4.0,4.0,4.0,4.0,3.0,1.0,4.0,2.0,3.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,NaN,3.0,3.0,3.0,2.0,2.0,3.0,3.0,NaN,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,5.0,1.0,3.0,1.0,1.0,4.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,3.0,1.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,1.0,2.0,0.0,1.0,2.0,3.0,1.0,1.0,4.0,4.0,4.0,4.0,3.0,3.0,2.0,5.0,1.0,1.0,1.0,1.0,4.0,4.0,5.0,5.0,1.0,1.0,NaN,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,1.0,1.0,2.0,1.0,5.0,5.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,5.0,5.0,NaN,NaN,NaN,5.0,5.0,5.0,3.0,3.0,3.0,4.0,4.0,4.0,4.0,3.0,3.0,1.0,1958.0,61.0,0.0,0.0,0.0,196.0,196.0,196.0,1.0,4.0,0.0,1580.0,1.0,2.0,2.0,3.0,1.0,1.0,1.0,1.0,8.0,8.0,10.0,2.0,0.0,2.0,2.0,3.0,3.0,196001.0
2,CYP,4.0,3.0,4.0,2.0,4.0,4.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,0.0,0.0,4.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,4.0,NaN,1.0,5.0,NaN,5.0,3.0,2.0,NaN,3.0,3.0,3.0,5.0,3.0,5.0,3.0,4.0,4.0,4.0,4.0,4.0,1.0,1.0,4.0,3.0,3.0,2.0,2.0,2.0,4.0,3.0,3.0,3.0,NaN,3.0,3.0,3.0,NaN,3.0,3.0,3.0,NaN,3.0,3.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,1.0,3.0,1.0,NaN,4.0,2.0,2.0,2.0,3.0,2.0,3.0,2.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,2.0,0.0,2.0,2.0,2.0,3.0,4.0,4.0,3.0,4.0,4.0,4.0,0.0,0.0,1.0,1.0,2.0,1.0,1.0,4.0,3.0,1.0,2.0,2.0,0.0,1.0,2.0,3.0,4.0,4.0,1.0,5.0,5.0,3.0,3.0,5.0,5.0,5.0,1.0,1.0,1.0,1.0,NaN,3.0,4.0,5.0,1.0,1.0,1.0,3.0,5.0,5.0,5.0,5.0,5.0,3.0,5.0,5.0,3.0,3.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,4.0,4.0,2.0,2.0,4.0,5.0,5.0,5.0,1.0,5.0,5.0,5.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,5.0,5.0,NaN,NaN,5.0,5.0,5.0,5.0,3.0,NaN,2.0,3.0,4.0,4.0,4.0,NaN,NaN,1.0,1977.0,42.0,1.0,1.0,1.0,804.0,804.0,804.0,1.0,6.0,0.0,1580.0,1.0,4.0,4.0,4.0,4.0,4.0,5.0,1.0,0.0,6.0,6.0,NaN,0.0,2.0,3.0,2.0,3.0,196001.0
3,CYP,4.0,3.0,4.0,1.0,4.0,4.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,2.0,2.0,2.0,2.0,2.0,5.0,2.0,NaN,3.0,5.0,4.0,4.0,5.0,NaN,1.0,1.0,NaN,3.0,3.0,3.0,3.0,3.0,4.0,2.0,4.0,4.0,4.0,3.0,1.0,4.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,3.0,3.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,3.0,NaN,NaN,2.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,3.0,3.0,2.0,1.0,3.0,2.0,2.0,2.0,2.0,NaN,4.0,2.0,1.0,2.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,2.0,2.0,3.0,4.0,4.0,4.0,4.0,4.0,4.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,2.0,2.0,1.0,0.0,2.0,1.0,1.0,2.0,1.0,4.0,3.0,4.0,5.0,5.0,3.0,3.0,5.0,1.0,1.0,1.0,1.0,3.0,2.0,5.0,4.0,1.0,0.0,NaN,3.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,3.0,3.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,NaN,NaN,2.0,1.0,1.0,5.0,1.0,1.0,1.0,1.0,1.0,4.0,1.0,1.0,1.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,4.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,4.0,2.0,3.0,1.0,4.0,NaN,NaN,1.0,4.0,NaN,3.0,5.0,NaN,5.0,5.0,NaN,NaN,5.0,NaN,5.0,5.0,3.0,3.0,NaN,4.0,4.0,4.0,4.0,2.0,2.0,1.0,1955.0,64.0,0.0,0.0,0.0,196.0,196.0,196.0,1.0,2.0,0.0,1580.0,1.0,2.0,4.0,2.0,1.0,2.0,1.0,4.0,8.0,6.0,9.0,2.0,0.0,2.0,3.0,3.0,3.0,196001.0
4,CYP,4.0,NaN,3.0,1.0,4.0,4.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,3.0,1.0,NaN,3.0,4.0,4.0,3.0,2.0,4.0,1.0,4.0,5.0,5.0,5.0,4.0,2.0,1.0,2.0,3.0,2.0,3.0,2.0,3.0,3.0,3.0,4.0,4.0,3.0,4.0,3.0,1.0,4.0,2.0,3.0,1.0,2.0,2.0,3.0,NaN,NaN,3.0,3.0,3.0,NaN,NaN,NaN,NaN,3.0,3.0,NaN,3.0,3.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,1.0,5.0,1.0,2.0,3.0,3.0,NaN,3.0,3.0,NaN,4.0,NaN,NaN,4.0,2.0,2.0,1.0,NaN,0.0,2.0,NaN,NaN,3.0,3.0,3.0,3.0,4.0,3.0,4.0,4.0,4.0,1.0,1.0,1.0,4.0,1.0,1.0,1.0,NaN,2.0,NaN,2.0,2.0,NaN,1.0,4.0,3.0,1.0,1.0,4.0,4.0,5.0,4.0,NaN,1.0,3.0,4.0,1.0,0.0,0.0,0.0,NaN,NaN,3.0,1.0,1.0,0.0,0.0,2.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,3.0,NaN,5.0,NaN,5.0,5.0,5.0,5.0,NaN,5.0,5.0,NaN,NaN,NaN,1.0,1.0,1.0,5.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,3.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,NaN,NaN,5.0,NaN,NaN,5.0,NaN,5.0,5.0,5.0,5.0,5.0,NaN,NaN,3.0,5.0,3.0,3.0,3.0,1.0,1.0,1.0,1967.0,52.0,1.0,1.0,1.0,100.0,100.0,100.0,1.0,8.0,0.0,9000.0,0.0,3.0,4.0,4.0,2.0,2.0,1.0,NaN,8.0,NaN,9.0,2.0,0.0,2.0,1.0,2.0,3.0,196001.0

In [11]:
df_fea_eng.shape

(95528, 292)

#### Drop Redundant Features

There are several features to be removed which may introduce noise or bias:
- Remove country variable.
- Remove race.
- Drop the questions about UN Security Council countries, IMF headquarters, and Amnesty International which focus on factual knowledge of international organizations rather than personal experiences, socioeconomic status, or well-being.
- Remove birth country for respondent and parents.
- Remove date of birth which is redundant with age.
- Party vote is not suitable to include in modelling.
- mother tongue is not ideal to include in predictive modelling.
- Drop those variables with spouse related because there are relied on marital status whereby a respondent with single status won't have spouse.

In [12]:
cols_to_ex = ['date_of_birth', 'party_vote', 'mother_tongue', 'country', 'race']
org_knowledge_cols = ['UN_country', 'IMF_head', 'Amn_Int_org_prob']
birth_cols = [c for c in df_fea_eng.columns if 'birth' in c.lower()]
spouse_cols = [c for c in df_fea_eng.columns if c.startswith('spouse_')]

cols_to_drop = cols_to_ex + spouse_cols + birth_cols + org_knowledge_cols
df_fea_eng = df_fea_eng.drop(columns=cols_to_drop)

In [13]:
df_fea_eng.shape

(95528, 278)

#### VIF

In [ ]:
def get_grouped_cols(cols_grp_name, exclude=None):
    """
    Return columns which contain any of the strings in cols_grp_name,
    optionally excluding columns that contain strings in 'exclude',
    but only if the exclude string is longer than the group name.

    cols_grp_name: str or list of str
    exclude: list of str
    """
    if exclude is None:
        exclude = []

    # Ensure cols_grp_name is a list
    if isinstance(cols_grp_name, str):
        cols_grp_name = [cols_grp_name]

    cols = []
    for col in df_fea_eng.columns:
        # Check if any of the group names are in the column
        if any(g in col for g in cols_grp_name):
            # Check exclude list
            to_exclude = False
            for e in exclude:
                if any(len(e) > len(g) and e in col for g in cols_grp_name):
                    to_exclude = True
                    break
            if not to_exclude:
                cols.append(col)
    return cols

Compare mean and median using simple impute to decide which to be used for each ordinal variable.

In [ ]:
def choose_mean_or_median(df, cols, mask_fraction=0.1, random_state=42):
    np.random.seed(random_state)

    total_mae_mean = 0
    total_mae_median = 0
    count = 0

    for col in cols:
        s = df[col].copy()
        if s.isna().all():
            continue

        mask = s.notna() & (np.random.rand(len(s)) < mask_fraction)
        if mask.sum() == 0:
            continue

        true_vals = s[mask].copy()
        s_masked = s.copy()
        s_masked[mask] = np.nan

        # Mean imputation
        mean_imp = SimpleImputer(strategy='mean').fit_transform(
            s_masked.values.reshape(-1,1)
        ).flatten()
        total_mae_mean += np.mean(np.abs(mean_imp[mask] - true_vals))

        # Median imputation
        median_imp = SimpleImputer(strategy='median').fit_transform(
            s_masked.values.reshape(-1,1)
        ).flatten()
        total_mae_median += np.mean(np.abs(median_imp[mask] - true_vals))

        count += 1

    # Final decision
    final_choice = "median" if total_mae_median < total_mae_mean else "mean"

    return {
        "final_choice": final_choice,
        "avg_mae_mean": total_mae_mean / count if count else None,
        "avg_mae_median": total_mae_median / count if count else None,
        "variables_used": count
    }

Exclude nominal data for imputing.

In [ ]:
# exclude the nominal data
filtered_vars = variable_table[~variable_table['Type'].isin(['Nominal'])]
cols_to_imp = [col for col in filtered_vars['New Variable Name'] if col in df_fea_eng.columns]

df_vif = df_fea_eng[cols_to_imp].copy()

In [ ]:
df_vif.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95528 entries, 0 to 95527
Columns: 261 entries, belonging1 to income_scale
dtypes: Int64(261)
memory usage: 214.0 MB

In [ ]:
# If range is not callable, restore it
if not callable(range):
    print("Restoring range function...")
    range = builtins.range
    len = builtins.len

def inter_vif(df, cols, target, threshold=10.0):

    df_use = df[cols].dropna().copy()
    temp_vars = cols.copy()

    kept_vars = []      # store HIGH VIF variables (VIF > 10)
    dropped = []        # store LOW VIF variables (≤ 10)
    no_multi_grp_vars = []  # store variables from group with no high-VIF

    print(f"\n🌟 Processing group with {len(cols)} variables:", cols)

    pbar = tqdm(desc=f"VIF loop ({cols[0].split('_')[0]})",
                total=len(cols), leave=False)

    while True:
        X = df_use[temp_vars].astype(np.float32).values

        # Compute VIF for all remaining vars
        vif_list = Parallel(n_jobs=-1)(
            delayed(variance_inflation_factor)(X, i)
            for i in range(X.shape[1])
        )

        vif_df = pd.DataFrame({"Feature": temp_vars, "VIF": vif_list})
        vif_df = vif_df.sort_values("VIF", ascending=False).reset_index(drop=True)

        max_vif = vif_df.iloc[0]["VIF"]
        worst = vif_df.iloc[0]["Feature"]

        # If highest VIF is HIGH → KEEP it
        if max_vif > threshold:
            kept_vars.append(worst)
            print(f"  → Added {worst} (VIF={max_vif:.2f})")

            temp_vars.remove(worst)     # remove from pool
            pbar.update(1)

        else:
            # All remaining variables are LOW VIF → drop them all
            for feat, v in zip(vif_df["Feature"], vif_df["VIF"]):
                dropped.append((feat, v))
                print(f"  → Dropped {feat} (VIF={v:.2f})")

            # If no high-VIF variable found at all, mark all as no_multicollinearity
            if len(kept_vars) == 0:
                no_multi_grp_vars.extend(temp_vars)
            break

        # Stop if only 1 variable left (no more VIF possible)
        if len(temp_vars) <= 1:
            break

    pbar.close()

    # Determine the winner among high-VIF variables (best correlation with target)
    if len(kept_vars) > 1:
        corrs = df[kept_vars].corrwith(df[target]).abs()
        winner = corrs.idxmax()
        winner_corr = corrs[winner]
    elif len(kept_vars) == 1:
        winner = kept_vars[0]
        winner_corr = df[winner].corr(df[target])
    else:
        winner = None
        winner_corr = None

    survivors = kept_vars  # all high-VIF variables

    if winner is not None:
        print(f"\nWinner: {winner} (|corr| = {winner_corr:.4f})")
    else:
        print("\nWinner: None")


    if no_multi_grp_vars:
        print(f"No-multicollinearity variables: {no_multi_grp_vars}")
    else:
        print(f"Survivors (high-VIF): {survivors}")

    return winner, survivors, no_multi_grp_vars, dropped


def intra_vif(df, cols, threshold=10.0):
    """
    Compute VIF for a group of variables (intra-group multicollinearity).

    Args:
        df (pd.DataFrame): DataFrame containing the variables.
        cols (list): List of column names to check.
        threshold (float): VIF threshold above which a variable is considered highly collinear.

    Returns:
        kept_vars (list): Variables kept (VIF ≤ threshold or manually kept).
        dropped (list): Variables dropped due to high VIF (> threshold).
    """

    df_use = df[cols].dropna().copy()
    temp_vars = cols.copy()

    kept_vars = []   # variables to keep
    dropped = []     # variables to drop due to high VIF

    print(f"\n🌟 Processing intra-VIF for {len(cols)} variables:", cols)

    pbar = tqdm(total=len(cols), desc="Intra-VIF loop", leave=False)

    while True:
        X = df_use[temp_vars].astype(np.float32).values

        # Compute VIF for all remaining variables
        vif_list = Parallel(n_jobs=-1)(
            delayed(variance_inflation_factor)(X, i) for i in range(X.shape[1])
        )

        vif_df = pd.DataFrame({"Feature": temp_vars, "VIF": vif_list})
        vif_df = vif_df.sort_values("VIF", ascending=False).reset_index(drop=True)

        max_vif = vif_df.iloc[0]["VIF"]
        worst = vif_df.iloc[0]["Feature"]

        if max_vif > threshold:
            # Drop the variable with highest VIF
            dropped.append(worst)
            temp_vars.remove(worst)
            print(f"  → Dropped {worst} (VIF={max_vif:.2f})")
        else:
            # All remaining variables are below threshold → keep them
            kept_vars.extend(temp_vars)
            break

        if len(temp_vars) <= 1:
            kept_vars.extend(temp_vars)
            break

        pbar.update(1)

    pbar.close()

    print(f"\nRemaining variables after intra-VIF: {kept_vars}")

    return kept_vars, dropped

Restoring range function...

In [ ]:
fractions = [0.10, 0.15, 0.20]
all_results = {}

for frac in fractions:
    results = choose_mean_or_median(df_vif, df_vif.columns, mask_fraction=frac)
    all_results[frac] = results

In [ ]:
for frac in fractions:
    print(frac, "→", all_results[frac]['final_choice'])

0.1 → median
0.15 → median
0.2 → median

Retrieve median and mean columns.

In [ ]:
# Imputer for median columns
imp_median = SimpleImputer(strategy='median')
df_median = pd.DataFrame(imp_median.fit_transform(df_vif), columns=df_vif.columns)

In [ ]:
df_imputed = df_median.copy().astype(int)
df_imputed.tail()

,belonging1,belonging2,esteem1,civic1,esteem2,belonging3,trust1,growth1,growth2,civic2,growth3,ethical1,ethical2,growth4,growth5,ethical3,ethical4,ethical5,ethical6,ethical7,ethical8,ethical9,ethical10,ethical11,ethical12,ethical13,esteem3,belonging4,ga_leaders_male_better,ga_edu_male_priority,ga_exec_male_better,esteem4,ga_jobs_male_priority,emp_prior_immig,ga_income_woman_problem,ethical14,civic3,civic4,ethical15,civic5,civic6,growth6,growth7,growth8,happy,physio1,esteem5,sact,safety1,physio2,safety2,physio3,safety3,safety4,esteem6,trust2,trust3,trust4,trust5,trust6,trust7,trust8,trust9,trust10,trust11,trust12,trust13,trust14,trust15,trust16,trust17,trust18,trust19,trust20,trust21,trust22,trust23,trust24,trust25,trust26,trust27,trust28,trust29,trust30,trust31,trust32,trust33,trust34,ethical16,civic7,civic8,civic9,civic10,civic11,civic12,civic13,civic14,civic15,civic16,civic17,civic18,income_eq_vs_diff,pri_vs_state,gov_vs_individual,comp_good_vs_harm,growth9,ethical17,ethical18,ethical19,ethical20,ethical21,ethical22,ethical23,ga_women_less_corrupt,ethical24,compassion1,civic19,compassion2,ethical25,compassion3,ethical26,compassion4,civic20,ethical27,safety5,safety6,safety7,safety8,safety9,safety10,safety11,safety12,safety13,safety14,safety15,safety16,safety17,safety18,safety19,safety20,safety21,safety22,civic21,growth10,civic22,ethical28,ethical29,growth11,ethical30,growth12,ethical31,growth13,ethical32,growth14,religious1,ethical33,trust35,growth15,religious2,religious3,religious4,ethical34,ethical35,ethical36,ethical37,ethical38,ethical39,ethical40,ethical41,ethical42,ethical43,ethical44,ethical45,ethical46,ethical47,ethical48,ethical49,ethical50,ethical51,ethical52,ethical53,ethical54,ethical55,ethical56,civic23,civic24,civic25,civic26,civic27,civic28,civic29,civic30,civic31,civic32,civic33,civic34,civic35,civic36,civic37,civic38,civic39,civic40,civic41,civic42,civic43,civic44,civic45,civic46,ethical57,ethical58,ethical59,ethical60,ethical61,ethical62,ethical63,ethical64,ethical65,ethical66,ethical67,civic47,ethical68,ethical69,ethical70,civic48,ethical71,l_vs_r_political,ethical72,ethical73,civic49,ethical74,ethical75,ethical76,ethical77,ethical78,ethical79,civic50,civic51,civic52,ethical80,civic53,growth16,growth17,growth18,growth19,growth20,sex,age,immigrant,mom_immigrant,dad_immigrant,citizenship,num_of_household,live_with_parent,marital_status,num_of_child,education_level,mom_education_level,dad_education_level,chief_wage,social_class,income_scale
95523,4,3,3,3,4,4,1,1,1,0,0,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,3,4,1,1,1,4,1,5,2,1,5,5,3,5,4,1,1,3,3,3,3,3,3,4,4,2,4,4,3,1,4,3,3,3,3,3,4,4,1,1,1,2,2,1,1,1,1,1,2,1,1,1,3,3,1,2,3,2,2,1,3,1,2,2,1,2,0,0,0,2,2,0,2,0,2,3,3,3,3,4,5,2,2,2,2,2,4,2,3,3,2,2,0,2,0,2,0,0,2,2,2,4,3,3,3,3,1,1,1,4,3,1,1,4,4,2,1,3,3,5,5,3,3,5,1,1,1,1,4,3,5,5,1,0,0,1,5,5,5,5,5,3,5,5,3,5,5,5,5,3,5,5,5,5,3,4,2,1,4,3,5,5,5,2,5,2,1,5,3,3,3,3,3,3,3,3,1,3,1,1,4,4,4,4,1,2,2,4,4,3,4,2,4,3,1,1,1,4,1,5,5,5,5,5,1,3,2,5,5,5,4,1,4,4,2,4,4,2,2,0,51,0,0,0,1,4,0,1,2,5,3,3,1,3,5
95524,4,4,3,3,4,4,0,1,0,0,0,1,0,1,1,1,0,1,0,1,0,1,0,1,0,0,3,3,1,1,1,4,1,1,1,2,3,4,3,4,2,2,3,3,4,3,4,5,5,4,4,2,4,4,1,2,4,3,3,3,3,3,3,3,2,2,3,3,3,2,2,2,3,3,2,2,2,3,3,3,2,3,2,2,3,2,3,2,3,2,0,0,0,0,0,0,0,0,0,0,0,3,3,3,2,4,4,3,3,3,3,2,3,2,4,4,2,2,2,2,2,2,2,2,4,4,2,4,4,2,4,3,1,1,1,2,1,1,1,2,2,2,1,4,4,2,1,5,4,5,1,1,1,1,4,4,5,5,1,0,0,5,5,5,5,5,5,5,5,5,3,5,5,5,5,5,5,5,5,5,4,3,3,2,3,3,3,5,5,5,4,5,5,4,3,2,3,3,3,3,3,3,3,3,2,1,4,4,4,4,3,4,3,4,4,4,4,4,4,4,1,1,1,4,1,4,4,2,5,4,1,5,2,4,5,5,4,2,2,2,4,3,3,2,2,0,35,0,0,0,1,4,0,1,2,5,3,3,1,3,3
95525,4,3,3,3,4,2,1,0,0,1,1,1,0,1,0,0,0,0,0,1,0,1,0,0,0,0,3,4,4,1,3,3,1,4,2,3,2,1,5,5,2,3,3,3,3,4,4,4,3,4,4,4,4,4,2,1,4,3,4,2,3,3,1,3,1,2,2,2,1,1,1,1,2,3,2,2,3,2,2,2,1,2,2,2,1,3,3,3,1,1,2,0,2,0,0,0,0,0,0,0,0,3,5,5,2,5,5,2,3,3,3,2,3,2,1,3,1,2,0,2,0,2,0,0,3,2,3,4,3,3,3,3,1,1,1,2,3,1,1,2,2,2,1,5,2,1,1,4,5,1,1,0,1,1,1,2,1,1,1,0,0,2,5,3,5,4,4,3,3,3,3,1,5,3,5,2,2,5,3,3,2,4,1,2,3,2,2,5,5,5,1,5,5,5,3,3,2,2,2,2,2,3,3,3,2,1,4,4,3,4,2,2,1,4,4,2,3,4,4,2,3,4,2,2,1,4,2,1,5,2,5,2,1,5,5,2,1,1,4,3,3,3,2,1,3,0,36,1,0,0,1,3,0,1,2,5,3,3,0,3,3
95526,4,3,3,2,3,1,1,0,0,1,0,0,0,0,0,1,1,1,0,1,0,1,0,0,0,1,4,2,2,2,2,3,2,4,4,4,2,2,4,5,4,2,3,3,4,4,5,5,5,4,4,4,4,4,3,2,4,3,3,3,2,2,2,4,1,2,2,4,3,2,2,2,3,3,1,3,3,2,2,2,1,2,2,2,2,2,2,3,1,0,0,0,0,0,0,0,0,0,0,0,0,4,1,4,1,4,5,2,2,3,4,1,4,2,2,3,1,2,2,2,0,2,2,2,4,4,4,4,4,4,4,4,1,1,1,2,4,1,1,3,2,2,1,3,4,2,2,5,5,1,0,0,0,0,1,1,1,1,0,0,0,5,2,5,5,3,5,2,4,2,4,1,5,1,5,5,5,5,1,4,3,4,1,1,1,2,1,5,4,1,1,5,1,2,3,1,1,3,1,2,1,1,3,3,1,1,3,3,3,3,3,3,1,3,2,4,4,4,3,4,1,1,1,4,1,5,2,2,5,5,1,5,4,4,5,5,4,1,3,4,2,2,3,1,1,0,57,0,0,0,1,4,0,1,2,5,3,3,1,3,3
95527,4,4,4,4,4,4,1,1,0,0,0,1,0,0,0,1,1,0,0,1,0,1,0,1,0,1,3,3,2,2,2,3,2,3,2,3,2,2,4,4,2,3,3,3,4,3,5,5,5,4,4,4,4,4,3,1,4,4,4,3,3,3,2,3,3,2,2,3,4,2,2,2,4,4,2,3,3,3,3,3,2,4,2,2,2,2,3,2,1,0,0,0,0,0,0,0,0,0,0,0,0,4,1,4,1,4,4,3,3,4,4,3,3,2,4,3,2,0,0,2,0,2,0,0,3,3,4,4,4,4,4,4,1,1,1,1,2,1,1,2,2,2,1,2,2,3,4,3,2,3,1,1,1,1,2,1,1,1,0,0,0,3,5,4,5,5,5,2,2,3,2,2,5,2,5,5,5,5,2,5,4,3,1,2,4,3,1,5,5,5,1,5,2,5,2,1,1,3,1,3,1,1,3,2,1,1,4,4,3,3,2,2,4,4,3,3,2,4,4,2,4,3,1,4,1,5,3,1,5,2,1,5,1,5,5,5,2,1,4,4,4,4,4,2,3,0,53,0,0,0,1,4,1,1,2,4,3,3,1,3,4

In [ ]:
target = 'happy'
# Your grouped columns (apply in inter-VIF)
groups = {
    "belonging": get_grouped_cols('belonging'),
    "esteem": get_grouped_cols('esteem'),
    "safety": get_grouped_cols('safety'),
    "physio": get_grouped_cols('physio'),
    "civic": get_grouped_cols('civic', exclude=['civic_']),
    "trust" : get_grouped_cols('trust'),
    "growth": get_grouped_cols('growth'),
    "ethical": get_grouped_cols('ethical', exclude=['ethical_']),
    "compassion": get_grouped_cols('compassion'),
    "education": get_grouped_cols('education'),
    "socioeconomic": get_grouped_cols(['social_class','income_scale', 'chief_wage']),
    "immigrant": get_grouped_cols('immigrant'),
    "religious": get_grouped_cols('religious'),
    "gender_attitudes": get_grouped_cols('ga_')
}

# non-grouped mainly for intra-VIF
flattened_grp_list = [item for sublist in groups.values() for item in sublist] # get all grouped columns in list form
non_grp_vars = df_imputed.select_dtypes(exclude='category').columns.difference(flattened_grp_list).to_list()
non_grp_vars = [c for c in non_grp_vars if c not in target] # exclude target (happy)

print("Grouped variables:\n", groups)
print("Ungrouped variables:\n", non_grp_vars)

Grouped variables:
 {'belonging': ['belonging1', 'belonging2', 'belonging3', 'belonging4'], 'esteem': ['esteem1', 'esteem2', 'esteem3', 'esteem4', 'esteem5', 'esteem6'], 'safety': ['safety1', 'safety2', 'safety3', 'safety4', 'safety5', 'safety6', 'safety7', 'safety8', 'safety9', 'safety10', 'safety11', 'safety12', 'safety13', 'safety14', 'safety15', 'safety16', 'safety17', 'safety18', 'safety19', 'safety20', 'safety21', 'safety22'], 'physio': ['physio1', 'physio2', 'physio3'], 'civic': ['civic1', 'civic2', 'civic3', 'civic4', 'civic5', 'civic6', 'civic7', 'civic8', 'civic9', 'civic10', 'civic11', 'civic12', 'civic13', 'civic14', 'civic15', 'civic16', 'civic17', 'civic18', 'civic19', 'civic20', 'civic21', 'civic22', 'civic23', 'civic24', 'civic25', 'civic26', 'civic27', 'civic28', 'civic29', 'civic30', 'civic31', 'civic32', 'civic33', 'civic34', 'civic35', 'civic36', 'civic37', 'civic38', 'civic39', 'civic40', 'civic41', 'civic42', 'civic43', 'civic44', 'civic45', 'civic46', 'civic47', 'civic48', 'civic49', 'civic50', 'civic51', 'civic52', 'civic53'], 'trust': ['trust1', 'trust2', 'trust3', 'trust4', 'trust5', 'trust6', 'trust7', 'trust8', 'trust9', 'trust10', 'trust11', 'trust12', 'trust13', 'trust14', 'trust15', 'trust16', 'trust17', 'trust18', 'trust19', 'trust20', 'trust21', 'trust22', 'trust23', 'trust24', 'trust25', 'trust26', 'trust27', 'trust28', 'trust29', 'trust30', 'trust31', 'trust32', 'trust33', 'trust34', 'trust35'], 'growth': ['growth1', 'growth2', 'growth3', 'growth4', 'growth5', 'growth6', 'growth7', 'growth8', 'growth9', 'growth10', 'growth11', 'growth12', 'growth13', 'growth14', 'growth15', 'growth16', 'growth17', 'growth18', 'growth19', 'growth20'], 'ethical': ['ethical1', 'ethical2', 'ethical3', 'ethical4', 'ethical5', 'ethical6', 'ethical7', 'ethical8', 'ethical9', 'ethical10', 'ethical11', 'ethical12', 'ethical13', 'ethical14', 'ethical15', 'ethical16', 'ethical17', 'ethical18', 'ethical19', 'ethical20', 'ethical21', 'ethical22', 'ethical23', 'ethical24', 'ethical25', 'ethical26', 'ethical27', 'ethical28', 'ethical29', 'ethical30', 'ethical31', 'ethical32', 'ethical33', 'ethical34', 'ethical35', 'ethical36', 'ethical37', 'ethical38', 'ethical39', 'ethical40', 'ethical41', 'ethical42', 'ethical43', 'ethical44', 'ethical45', 'ethical46', 'ethical47', 'ethical48', 'ethical49', 'ethical50', 'ethical51', 'ethical52', 'ethical53', 'ethical54', 'ethical55', 'ethical56', 'ethical57', 'ethical58', 'ethical59', 'ethical60', 'ethical61', 'ethical62', 'ethical63', 'ethical64', 'ethical65', 'ethical66', 'ethical67', 'ethical68', 'ethical69', 'ethical70', 'ethical71', 'ethical72', 'ethical73', 'ethical74', 'ethical75', 'ethical76', 'ethical77', 'ethical78', 'ethical79', 'ethical80'], 'compassion': ['compassion1', 'compassion2', 'compassion3', 'compassion4'], 'education': ['education_level', 'mom_education_level', 'dad_education_level'], 'socioeconomic': ['chief_wage', 'social_class', 'income_scale'], 'immigrant': ['immigrant', 'mom_immigrant', 'dad_immigrant'], 'religious': ['religious1', 'religious2', 'religious3', 'religious4'], 'gender_attitudes': ['ga_leaders_male_better', 'ga_edu_male_priority', 'ga_exec_male_better', 'ga_jobs_male_priority', 'ga_income_woman_problem', 'ga_women_less_corrupt']}
Ungrouped variables:
 ['age', 'citizenship', 'comp_good_vs_harm', 'emp_prior_immig', 'gov_vs_individual', 'income_eq_vs_diff', 'l_vs_r_political', 'live_with_parent', 'marital_status', 'num_of_child', 'num_of_household', 'pri_vs_state', 'sact', 'sex']

In [ ]:
dropped_vars = {}
winner_grp_var = {}
survived_vars = {}
non_multi_corr_grp_vars = {} # track group variables with no high VIF
for name, cols in groups.items():
    print(f"\n{'='*8} Processing category: {name} {'='*8}")

    winner, kept_vars, non_multi_corr_vars, dropped = inter_vif(
        df_imputed,
        cols,
        target='happy',
        threshold=10
    )

    winner_grp_var[name] = winner
    dropped_vars[name] = dropped
    survived_vars[name] = kept_vars  # kept vars for questionnaires from same group

    if non_multi_corr_vars:
        non_multi_corr_grp_vars[name] = non_multi_corr_vars


print("\nFinal inter-VIF winners:", winner_grp_var)

======== Processing category: belonging ========

🌟 Processing group with 4 variables: ['belonging1', 'belonging2', 'belonging3', 'belonging4']

VIF loop (belonging1):  25%|██▌       | 1/4 [00:02<00:06,  2.28s/it]

  → Added belonging1 (VIF=35.15)

  → Added belonging2 (VIF=11.01)
  → Dropped belonging4 (VIF=3.97)
  → Dropped belonging3 (VIF=3.97)

Winner: belonging1 (|corr| = 0.1059)
Survivors (high-VIF): ['belonging1', 'belonging2']

======== Processing category: esteem ========

🌟 Processing group with 6 variables: ['esteem1', 'esteem2', 'esteem3', 'esteem4', 'esteem5', 'esteem6']

VIF loop (esteem1):  33%|███▎      | 2/6 [00:01<00:02,  1.84it/s]

  → Added esteem3 (VIF=19.42)
  → Added esteem2 (VIF=15.22)

  → Added esteem1 (VIF=11.97)
  → Dropped esteem5 (VIF=8.57)
  → Dropped esteem4 (VIF=7.28)
  → Dropped esteem6 (VIF=6.41)

Winner: esteem3 (|corr| = 0.1085)
Survivors (high-VIF): ['esteem3', 'esteem2', 'esteem1']

======== Processing category: safety ========

🌟 Processing group with 22 variables: ['safety1', 'safety2', 'safety3', 'safety4', 'safety5', 'safety6', 'safety7', 'safety8', 'safety9', 'safety10', 'safety11', 'safety12', 'safety13', 'safety14', 'safety15', 'safety16', 'safety17', 'safety18', 'safety19', 'safety20', 'safety21', 'safety22']

VIF loop (safety1):   5%|▍         | 1/22 [00:02<00:51,  2.48s/it]

  → Added safety4 (VIF=35.84)

VIF loop (safety1):   9%|▉         | 2/22 [00:04<00:46,  2.31s/it]

  → Added safety12 (VIF=35.35)

VIF loop (safety1):  14%|█▎        | 3/22 [00:06<00:40,  2.15s/it]

  → Added safety8 (VIF=29.94)

VIF loop (safety1):  18%|█▊        | 4/22 [00:08<00:36,  2.03s/it]

  → Added safety11 (VIF=26.07)

VIF loop (safety1):  23%|██▎       | 5/22 [00:09<00:30,  1.78s/it]

  → Added safety21 (VIF=25.80)

VIF loop (safety1):  27%|██▋       | 6/22 [00:10<00:25,  1.58s/it]

  → Added safety9 (VIF=24.61)

VIF loop (safety1):  32%|███▏      | 7/22 [00:11<00:20,  1.36s/it]

  → Added safety6 (VIF=21.71)

VIF loop (safety1):  36%|███▋      | 8/22 [00:12<00:16,  1.18s/it]

  → Added safety2 (VIF=20.88)

VIF loop (safety1):  41%|████      | 9/22 [00:13<00:13,  1.03s/it]

  → Added safety20 (VIF=18.16)

VIF loop (safety1):  45%|████▌     | 10/22 [00:14<00:11,  1.09it/s]

  → Added safety10 (VIF=17.57)

VIF loop (safety1):  50%|█████     | 11/22 [00:14<00:08,  1.31it/s]

  → Added safety5 (VIF=15.15)

VIF loop (safety1):  55%|█████▍    | 12/22 [00:14<00:06,  1.54it/s]

  → Added safety17 (VIF=13.76)

VIF loop (safety1):  59%|█████▉    | 13/22 [00:15<00:04,  1.81it/s]

  → Added safety18 (VIF=13.37)

VIF loop (safety1):  64%|██████▎   | 14/22 [00:15<00:03,  2.13it/s]

  → Added safety3 (VIF=11.90)

  → Added safety15 (VIF=11.13)
  → Dropped safety16 (VIF=7.81)
  → Dropped safety7 (VIF=7.81)
  → Dropped safety19 (VIF=7.79)
  → Dropped safety22 (VIF=7.53)
  → Dropped safety1 (VIF=7.43)
  → Dropped safety13 (VIF=3.39)
  → Dropped safety14 (VIF=2.90)

Winner: safety5 (|corr| = 0.1916)
Survivors (high-VIF): ['safety4', 'safety12', 'safety8', 'safety11', 'safety21', 'safety9', 'safety6', 'safety2', 'safety20', 'safety10', 'safety5', 'safety17', 'safety18', 'safety3', 'safety15']

======== Processing category: physio ========

🌟 Processing group with 3 variables: ['physio1', 'physio2', 'physio3']

  → Added physio2 (VIF=20.50)
  → Added physio1 (VIF=10.35)

Winner: physio1 (|corr| = 0.3691)
Survivors (high-VIF): ['physio2', 'physio1']

======== Processing category: civic ========

🌟 Processing group with 53 variables: ['civic1', 'civic2', 'civic3', 'civic4', 'civic5', 'civic6', 'civic7', 'civic8', 'civic9', 'civic10', 'civic11', 'civic12', 'civic13', 'civic14', 'civic15', 'civic16', 'civic17', 'civic18', 'civic19', 'civic20', 'civic21', 'civic22', 'civic23', 'civic24', 'civic25', 'civic26', 'civic27', 'civic28', 'civic29', 'civic30', 'civic31', 'civic32', 'civic33', 'civic34', 'civic35', 'civic36', 'civic37', 'civic38', 'civic39', 'civic40', 'civic41', 'civic42', 'civic43', 'civic44', 'civic45', 'civic46', 'civic47', 'civic48', 'civic49', 'civic50', 'civic51', 'civic52', 'civic53']

VIF loop (civic1):   2%|▏         | 1/53 [00:23<20:43, 23.91s/it]

  → Added civic46 (VIF=34.85)

VIF loop (civic1):   4%|▍         | 2/53 [00:46<19:36, 23.07s/it]

  → Added civic50 (VIF=26.11)

VIF loop (civic1):   6%|▌         | 3/53 [01:07<18:30, 22.22s/it]

  → Added civic53 (VIF=23.27)

VIF loop (civic1):   8%|▊         | 4/53 [01:26<17:02, 20.86s/it]

  → Added civic5 (VIF=21.19)

VIF loop (civic1):   9%|▉         | 5/53 [01:44<15:54, 19.88s/it]

  → Added civic36 (VIF=19.57)

VIF loop (civic1):  11%|█▏        | 6/53 [02:00<14:35, 18.63s/it]

  → Added civic48 (VIF=19.06)

VIF loop (civic1):  13%|█▎        | 7/53 [02:17<13:41, 17.87s/it]

  → Added civic4 (VIF=18.21)

VIF loop (civic1):  15%|█▌        | 8/53 [02:31<12:31, 16.69s/it]

  → Added civic45 (VIF=17.78)

VIF loop (civic1):  17%|█▋        | 9/53 [02:44<11:26, 15.61s/it]

  → Added civic49 (VIF=14.16)

VIF loop (civic1):  19%|█▉        | 10/53 [02:56<10:30, 14.66s/it]

  → Added civic43 (VIF=13.84)

VIF loop (civic1):  21%|██        | 11/53 [03:09<09:52, 14.10s/it]

  → Added civic30 (VIF=13.76)

VIF loop (civic1):  23%|██▎       | 12/53 [03:21<09:02, 13.23s/it]

  → Added civic22 (VIF=13.23)

VIF loop (civic1):  25%|██▍       | 13/53 [03:31<08:14, 12.37s/it]

  → Added civic51 (VIF=12.82)

VIF loop (civic1):  26%|██▋       | 14/53 [03:42<07:50, 12.06s/it]

  → Added civic24 (VIF=12.60)

VIF loop (civic1):  28%|██▊       | 15/53 [07:34<49:38, 78.38s/it]

  → Added civic26 (VIF=11.98)

VIF loop (civic1):  30%|███       | 16/53 [07:44<35:38, 57.81s/it]

  → Added civic33 (VIF=11.88)

VIF loop (civic1):  32%|███▏      | 17/53 [14:24<1:36:19, 160.55s/it]

  → Added civic41 (VIF=10.64)

VIF loop (civic1):  34%|███▍      | 18/53 [17:19<1:36:07, 164.79s/it]

  → Added civic6 (VIF=10.54)

VIF loop (civic1):  36%|███▌      | 19/53 [22:06<1:54:14, 201.59s/it]

  → Added civic23 (VIF=10.46)

VIF loop (civic1):  38%|███▊      | 20/53 [24:24<1:40:24, 182.55s/it]

  → Added civic44 (VIF=10.11)

  → Dropped civic32 (VIF=9.93)
  → Dropped civic35 (VIF=9.89)
  → Dropped civic38 (VIF=9.88)
  → Dropped civic34 (VIF=9.73)
  → Dropped civic40 (VIF=9.66)
  → Dropped civic47 (VIF=9.38)
  → Dropped civic39 (VIF=9.27)
  → Dropped civic42 (VIF=9.21)
  → Dropped civic37 (VIF=8.87)
  → Dropped civic28 (VIF=8.64)
  → Dropped civic1 (VIF=7.78)
  → Dropped civic31 (VIF=7.59)
  → Dropped civic3 (VIF=6.82)
  → Dropped civic52 (VIF=6.74)
  → Dropped civic29 (VIF=5.19)
  → Dropped civic27 (VIF=4.75)
  → Dropped civic25 (VIF=4.46)
  → Dropped civic21 (VIF=3.87)
  → Dropped civic19 (VIF=2.98)
  → Dropped civic2 (VIF=2.77)
  → Dropped civic14 (VIF=2.01)
  → Dropped civic12 (VIF=1.99)
  → Dropped civic20 (VIF=1.98)
  → Dropped civic9 (VIF=1.88)
  → Dropped civic15 (VIF=1.88)
  → Dropped civic16 (VIF=1.88)
  → Dropped civic7 (VIF=1.84)
  → Dropped civic13 (VIF=1.78)
  → Dropped civic8 (VIF=1.78)
  → Dropped civic17 (VIF=1.71)
  → Dropped civic10 (VIF=1.63)
  → Dropped civic11 (VIF=1.62)
  → Dropped civic18 (VIF=1.36)

Winner: civic53 (|corr| = 0.1798)
Survivors (high-VIF): ['civic46', 'civic50', 'civic53', 'civic5', 'civic36', 'civic48', 'civic4', 'civic45', 'civic49', 'civic43', 'civic30', 'civic22', 'civic51', 'civic24', 'civic26', 'civic33', 'civic41', 'civic6', 'civic23', 'civic44']

======== Processing category: trust ========

🌟 Processing group with 35 variables: ['trust1', 'trust2', 'trust3', 'trust4', 'trust5', 'trust6', 'trust7', 'trust8', 'trust9', 'trust10', 'trust11', 'trust12', 'trust13', 'trust14', 'trust15', 'trust16', 'trust17', 'trust18', 'trust19', 'trust20', 'trust21', 'trust22', 'trust23', 'trust24', 'trust25', 'trust26', 'trust27', 'trust28', 'trust29', 'trust30', 'trust31', 'trust32', 'trust33', 'trust34', 'trust35']

VIF loop (trust1):   3%|▎         | 1/35 [00:14<08:22, 14.79s/it]

  → Added trust3 (VIF=32.96)

VIF loop (trust1):   6%|▌         | 2/35 [00:22<05:58, 10.87s/it]

  → Added trust25 (VIF=22.65)

VIF loop (trust1):   9%|▊         | 3/35 [00:28<04:29,  8.42s/it]

  → Added trust32 (VIF=21.93)

VIF loop (trust1):  11%|█▏        | 4/35 [00:34<03:47,  7.35s/it]

  → Added trust33 (VIF=21.33)

VIF loop (trust1):  14%|█▍        | 5/35 [00:39<03:14,  6.50s/it]

  → Added trust5 (VIF=20.74)

VIF loop (trust1):  17%|█▋        | 6/35 [00:43<02:44,  5.68s/it]

  → Added trust29 (VIF=19.72)

VIF loop (trust1):  20%|██        | 7/35 [00:47<02:22,  5.07s/it]

  → Added trust18 (VIF=19.37)

VIF loop (trust1):  23%|██▎       | 8/35 [00:51<02:15,  5.03s/it]

  → Added trust20 (VIF=18.92)

VIF loop (trust1):  26%|██▌       | 9/35 [00:55<01:57,  4.51s/it]

  → Added trust15 (VIF=18.58)

VIF loop (trust1):  29%|██▊       | 10/35 [00:58<01:40,  4.01s/it]

  → Added trust26 (VIF=17.83)

VIF loop (trust1):  31%|███▏      | 11/35 [01:00<01:25,  3.56s/it]

  → Added trust30 (VIF=17.73)

VIF loop (trust1):  34%|███▍      | 12/35 [01:03<01:14,  3.22s/it]

  → Added trust12 (VIF=17.02)

VIF loop (trust1):  37%|███▋      | 13/35 [01:05<01:05,  2.99s/it]

  → Added trust7 (VIF=16.98)

VIF loop (trust1):  40%|████      | 14/35 [01:07<00:56,  2.71s/it]

  → Added trust28 (VIF=16.58)

VIF loop (trust1):  43%|████▎     | 15/35 [01:09<00:48,  2.45s/it]

  → Added trust19 (VIF=16.45)

VIF loop (trust1):  46%|████▌     | 16/35 [01:11<00:42,  2.22s/it]

  → Added trust4 (VIF=16.16)

VIF loop (trust1):  49%|████▊     | 17/35 [01:12<00:35,  2.00s/it]

  → Added trust34 (VIF=15.70)

VIF loop (trust1):  51%|█████▏    | 18/35 [01:15<00:36,  2.13s/it]

  → Added trust22 (VIF=15.34)

VIF loop (trust1):  54%|█████▍    | 19/35 [01:16<00:28,  1.80s/it]

  → Added trust10 (VIF=15.20)

VIF loop (trust1):  57%|█████▋    | 20/35 [01:17<00:22,  1.50s/it]

  → Added trust24 (VIF=14.70)

VIF loop (trust1):  60%|██████    | 21/35 [01:17<00:17,  1.26s/it]

  → Added trust16 (VIF=14.11)

VIF loop (trust1):  63%|██████▎   | 22/35 [01:18<00:13,  1.06s/it]

  → Added trust27 (VIF=12.81)

VIF loop (trust1):  66%|██████▌   | 23/35 [01:18<00:10,  1.12it/s]

  → Added trust14 (VIF=12.22)

VIF loop (trust1):  69%|██████▊   | 24/35 [01:19<00:08,  1.34it/s]

  → Added trust23 (VIF=11.69)

VIF loop (trust1):  71%|███████▏  | 25/35 [01:19<00:06,  1.60it/s]

  → Added trust13 (VIF=11.49)

VIF loop (trust1):  74%|███████▍  | 26/35 [01:19<00:04,  1.89it/s]

  → Added trust21 (VIF=11.04)

VIF loop (trust1):  77%|███████▋  | 27/35 [01:20<00:03,  2.23it/s]

  → Added trust9 (VIF=10.52)

  → Added trust6 (VIF=10.17)
  → Dropped trust11 (VIF=9.64)
  → Dropped trust31 (VIF=9.22)
  → Dropped trust2 (VIF=8.95)
  → Dropped trust17 (VIF=8.05)
  → Dropped trust8 (VIF=7.76)
  → Dropped trust1 (VIF=3.82)
  → Dropped trust35 (VIF=3.50)

Winner: trust3 (|corr| = 0.1347)
Survivors (high-VIF): ['trust3', 'trust25', 'trust32', 'trust33', 'trust5', 'trust29', 'trust18', 'trust20', 'trust15', 'trust26', 'trust30', 'trust12', 'trust7', 'trust28', 'trust19', 'trust4', 'trust34', 'trust22', 'trust10', 'trust24', 'trust16', 'trust27', 'trust14', 'trust23', 'trust13', 'trust21', 'trust9', 'trust6']

======== Processing category: growth ========

🌟 Processing group with 20 variables: ['growth1', 'growth2', 'growth3', 'growth4', 'growth5', 'growth6', 'growth7', 'growth8', 'growth9', 'growth10', 'growth11', 'growth12', 'growth13', 'growth14', 'growth15', 'growth16', 'growth17', 'growth18', 'growth19', 'growth20']

VIF loop (growth1):   5%|▌         | 1/20 [00:01<00:30,  1.61s/it]

  → Added growth17 (VIF=36.34)

VIF loop (growth1):  10%|█         | 2/20 [00:02<00:25,  1.41s/it]

  → Added growth18 (VIF=27.33)

VIF loop (growth1):  15%|█▌        | 3/20 [00:03<00:21,  1.27s/it]

  → Added growth16 (VIF=21.14)

VIF loop (growth1):  20%|██        | 4/20 [00:04<00:18,  1.14s/it]

  → Added growth7 (VIF=17.38)

VIF loop (growth1):  25%|██▌       | 5/20 [00:05<00:15,  1.03s/it]

  → Added growth12 (VIF=16.03)

VIF loop (growth1):  30%|███       | 6/20 [00:06<00:12,  1.11it/s]

  → Added growth19 (VIF=15.25)

VIF loop (growth1):  35%|███▌      | 7/20 [00:06<00:10,  1.27it/s]

  → Added growth10 (VIF=11.16)

  → Dropped growth8 (VIF=9.78)
  → Dropped growth15 (VIF=7.69)
  → Dropped growth20 (VIF=7.05)
  → Dropped growth14 (VIF=6.77)
  → Dropped growth9 (VIF=6.76)
  → Dropped growth11 (VIF=6.30)
  → Dropped growth13 (VIF=5.34)
  → Dropped growth6 (VIF=4.90)
  → Dropped growth2 (VIF=2.12)
  → Dropped growth5 (VIF=1.94)
  → Dropped growth1 (VIF=1.78)
  → Dropped growth4 (VIF=1.50)
  → Dropped growth3 (VIF=1.31)

Winner: growth16 (|corr| = 0.0910)
Survivors (high-VIF): ['growth17', 'growth18', 'growth16', 'growth7', 'growth12', 'growth19', 'growth10']

======== Processing category: ethical ========

🌟 Processing group with 80 variables: ['ethical1', 'ethical2', 'ethical3', 'ethical4', 'ethical5', 'ethical6', 'ethical7', 'ethical8', 'ethical9', 'ethical10', 'ethical11', 'ethical12', 'ethical13', 'ethical14', 'ethical15', 'ethical16', 'ethical17', 'ethical18', 'ethical19', 'ethical20', 'ethical21', 'ethical22', 'ethical23', 'ethical24', 'ethical25', 'ethical26', 'ethical27', 'ethical28', 'ethical29', 'ethical30', 'ethical31', 'ethical32', 'ethical33', 'ethical34', 'ethical35', 'ethical36', 'ethical37', 'ethical38', 'ethical39', 'ethical40', 'ethical41', 'ethical42', 'ethical43', 'ethical44', 'ethical45', 'ethical46', 'ethical47', 'ethical48', 'ethical49', 'ethical50', 'ethical51', 'ethical52', 'ethical53', 'ethical54', 'ethical55', 'ethical56', 'ethical57', 'ethical58', 'ethical59', 'ethical60', 'ethical61', 'ethical62', 'ethical63', 'ethical64', 'ethical65', 'ethical66', 'ethical67', 'ethical68', 'ethical69', 'ethical70', 'ethical71', 'ethical72', 'ethical73', 'ethical74', 'ethical75', 'ethical76', 'ethical77', 'ethical78', 'ethical79', 'ethical80']

VIF loop (ethical1):   1%|▏         | 1/80 [01:15<1:39:01, 75.21s/it]

  → Added ethical50 (VIF=78.33)

VIF loop (ethical1):   2%|▎         | 2/80 [02:17<1:27:45, 67.51s/it]

  → Added ethical37 (VIF=70.45)

VIF loop (ethical1):   4%|▍         | 3/80 [03:42<1:37:09, 75.71s/it]

  → Added ethical49 (VIF=63.10)

VIF loop (ethical1):   5%|▌         | 4/80 [05:11<1:42:14, 80.71s/it]

  → Added ethical47 (VIF=56.72)

VIF loop (ethical1):   6%|▋         | 5/80 [06:20<1:35:39, 76.52s/it]

  → Added ethical39 (VIF=52.81)

VIF loop (ethical1):   8%|▊         | 6/80 [07:21<1:28:04, 71.42s/it]

  → Added ethical52 (VIF=43.64)

VIF loop (ethical1):   9%|▉         | 7/80 [08:49<1:33:15, 76.65s/it]

  → Added ethical38 (VIF=31.78)

VIF loop (ethical1):  10%|█         | 8/80 [10:13<1:34:43, 78.94s/it]

  → Added ethical45 (VIF=27.55)

VIF loop (ethical1):  11%|█▏        | 9/80 [11:20<1:29:12, 75.39s/it]

  → Added ethical20 (VIF=25.99)

VIF loop (ethical1):  12%|█▎        | 10/80 [12:17<1:21:15, 69.65s/it]

  → Added ethical41 (VIF=25.80)

VIF loop (ethical1):  14%|█▍        | 11/80 [13:17<1:16:38, 66.64s/it]

  → Added ethical67 (VIF=24.19)

VIF loop (ethical1):  15%|█▌        | 12/80 [14:20<1:14:25, 65.66s/it]

  → Added ethical21 (VIF=22.29)

VIF loop (ethical1):  16%|█▋        | 13/80 [15:28<1:14:09, 66.42s/it]

  → Added ethical19 (VIF=20.38)

VIF loop (ethical1):  18%|█▊        | 14/80 [16:27<1:10:36, 64.19s/it]

  → Added ethical79 (VIF=20.19)

VIF loop (ethical1):  19%|█▉        | 15/80 [17:22<1:06:17, 61.19s/it]

  → Added ethical42 (VIF=19.19)

VIF loop (ethical1):  20%|██        | 16/80 [18:06<1:00:01, 56.27s/it]

  → Added ethical36 (VIF=17.99)

VIF loop (ethical1):  21%|██▏       | 17/80 [19:03<59:12, 56.38s/it]

  → Added ethical64 (VIF=17.32)

VIF loop (ethical1):  22%|██▎       | 18/80 [19:51<55:41, 53.90s/it]

  → Added ethical51 (VIF=17.23)

VIF loop (ethical1):  24%|██▍       | 19/80 [20:33<51:06, 50.26s/it]

  → Added ethical66 (VIF=16.86)

VIF loop (ethical1):  25%|██▌       | 20/80 [21:18<48:32, 48.54s/it]

  → Added ethical62 (VIF=16.49)

VIF loop (ethical1):  26%|██▋       | 21/80 [22:06<47:45, 48.56s/it]

  → Added ethical22 (VIF=16.10)

VIF loop (ethical1):  28%|██▊       | 22/80 [22:50<45:34, 47.14s/it]

  → Added ethical40 (VIF=15.89)

VIF loop (ethical1):  29%|██▉       | 23/80 [23:15<38:21, 40.38s/it]

  → Added ethical48 (VIF=15.75)

VIF loop (ethical1):  30%|███       | 24/80 [23:37<32:47, 35.13s/it]

  → Added ethical76 (VIF=15.34)

VIF loop (ethical1):  31%|███▏      | 25/80 [24:13<32:15, 35.19s/it]

  → Added ethical17 (VIF=14.80)

VIF loop (ethical1):  32%|███▎      | 26/80 [24:37<28:40, 31.86s/it]

  → Added ethical57 (VIF=14.22)

VIF loop (ethical1):  34%|███▍      | 27/80 [24:56<24:52, 28.16s/it]

  → Added ethical80 (VIF=13.44)

VIF loop (ethical1):  35%|███▌      | 28/80 [25:15<21:55, 25.30s/it]

  → Added ethical15 (VIF=13.32)

VIF loop (ethical1):  36%|███▋      | 29/80 [25:32<19:22, 22.80s/it]

  → Added ethical23 (VIF=13.20)

VIF loop (ethical1):  38%|███▊      | 30/80 [25:48<17:20, 20.81s/it]

  → Added ethical58 (VIF=13.04)

VIF loop (ethical1):  39%|███▉      | 31/80 [26:04<15:48, 19.35s/it]

  → Added ethical44 (VIF=12.73)

VIF loop (ethical1):  40%|████      | 32/80 [35:57<2:33:09, 191.44s/it]

  → Added ethical65 (VIF=12.36)

VIF loop (ethical1):  41%|████▏     | 33/80 [36:11<1:48:09, 138.07s/it]

  → Added ethical35 (VIF=11.99)

VIF loop (ethical1):  42%|████▎     | 34/80 [53:26<5:12:12, 407.22s/it]

  → Added ethical30 (VIF=11.78)

VIF loop (ethical1):  44%|████▍     | 35/80 [1:08:43<7:00:11, 560.25s/it]

  → Added ethical46 (VIF=11.64)

VIF loop (ethical1):  45%|████▌     | 36/80 [1:24:39<8:17:49, 678.86s/it]

  → Added ethical60 (VIF=11.27)

VIF loop (ethical1):  46%|████▋     | 37/80 [1:25:14<5:48:04, 485.68s/it]

  → Added ethical69 (VIF=10.95)

VIF loop (ethical1):  48%|████▊     | 38/80 [1:25:24<4:00:06, 343.02s/it]

  → Added ethical18 (VIF=10.83)

VIF loop (ethical1):  49%|████▉     | 39/80 [1:25:33<2:45:58, 242.89s/it]

  → Added ethical74 (VIF=10.56)

  → Dropped ethical54 (VIF=9.91)
  → Dropped ethical33 (VIF=9.52)
  → Dropped ethical55 (VIF=9.47)
  → Dropped ethical61 (VIF=9.36)
  → Dropped ethical24 (VIF=8.45)
  → Dropped ethical71 (VIF=8.08)
  → Dropped ethical72 (VIF=8.08)
  → Dropped ethical14 (VIF=8.02)
  → Dropped ethical59 (VIF=7.95)
  → Dropped ethical56 (VIF=7.91)
  → Dropped ethical70 (VIF=7.86)
  → Dropped ethical68 (VIF=7.81)
  → Dropped ethical78 (VIF=7.79)
  → Dropped ethical77 (VIF=7.75)
  → Dropped ethical31 (VIF=7.70)
  → Dropped ethical53 (VIF=7.70)
  → Dropped ethical43 (VIF=7.69)
  → Dropped ethical29 (VIF=7.65)
  → Dropped ethical63 (VIF=7.39)
  → Dropped ethical28 (VIF=7.14)
  → Dropped ethical16 (VIF=6.74)
  → Dropped ethical34 (VIF=6.11)
  → Dropped ethical75 (VIF=6.02)
  → Dropped ethical73 (VIF=5.43)
  → Dropped ethical32 (VIF=3.79)
  → Dropped ethical9 (VIF=3.69)
  → Dropped ethical7 (VIF=3.58)
  → Dropped ethical26 (VIF=3.41)
  → Dropped ethical25 (VIF=3.36)
  → Dropped ethical1 (VIF=2.78)
  → Dropped ethical27 (VIF=2.77)
  → Dropped ethical12 (VIF=1.94)
  → Dropped ethical6 (VIF=1.92)
  → Dropped ethical10 (VIF=1.88)
  → Dropped ethical8 (VIF=1.84)
  → Dropped ethical11 (VIF=1.78)
  → Dropped ethical13 (VIF=1.75)
  → Dropped ethical4 (VIF=1.55)
  → Dropped ethical5 (VIF=1.47)
  → Dropped ethical2 (VIF=1.44)
  → Dropped ethical3 (VIF=1.42)

Winner: ethical80 (|corr| = 0.1355)
Survivors (high-VIF): ['ethical50', 'ethical37', 'ethical49', 'ethical47', 'ethical39', 'ethical52', 'ethical38', 'ethical45', 'ethical20', 'ethical41', 'ethical67', 'ethical21', 'ethical19', 'ethical79', 'ethical42', 'ethical36', 'ethical64', 'ethical51', 'ethical66', 'ethical62', 'ethical22', 'ethical40', 'ethical48', 'ethical76', 'ethical17', 'ethical57', 'ethical80', 'ethical15', 'ethical23', 'ethical58', 'ethical44', 'ethical65', 'ethical35', 'ethical30', 'ethical46', 'ethical60', 'ethical69', 'ethical18', 'ethical74']

======== Processing category: compassion ========

🌟 Processing group with 4 variables: ['compassion1', 'compassion2', 'compassion3', 'compassion4']

  → Dropped compassion1 (VIF=4.84)
  → Dropped compassion4 (VIF=4.27)
  → Dropped compassion2 (VIF=3.69)
  → Dropped compassion3 (VIF=3.12)

Winner: None
No-multicollinearity variables: ['compassion1', 'compassion2', 'compassion3', 'compassion4']

======== Processing category: education ========

🌟 Processing group with 3 variables: ['education_level', 'mom_education_level', 'dad_education_level']

VIF loop (education):  33%|███▎      | 1/3 [00:00<00:00,  5.85it/s]

  → Added dad_education_level (VIF=17.47)

  → Dropped education_level (VIF=7.57)
  → Dropped mom_education_level (VIF=7.57)

Winner: dad_education_level (|corr| = 0.0429)
Survivors (high-VIF): ['dad_education_level']

======== Processing category: socioeconomic ========

🌟 Processing group with 3 variables: ['chief_wage', 'social_class', 'income_scale']

  → Dropped social_class (VIF=9.00)
  → Dropped income_scale (VIF=8.81)
  → Dropped chief_wage (VIF=1.71)

Winner: None
No-multicollinearity variables: ['chief_wage', 'social_class', 'income_scale']

======== Processing category: immigrant ========

🌟 Processing group with 3 variables: ['immigrant', 'mom_immigrant', 'dad_immigrant']

  → Dropped mom_immigrant (VIF=3.17)
  → Dropped dad_immigrant (VIF=3.06)
  → Dropped immigrant (VIF=1.50)

Winner: None
No-multicollinearity variables: ['immigrant', 'mom_immigrant', 'dad_immigrant']

======== Processing category: religious ========

🌟 Processing group with 4 variables: ['religious1', 'religious2', 'religious3', 'religious4']

  → Dropped religious1 (VIF=3.79)
  → Dropped religious2 (VIF=3.07)
  → Dropped religious4 (VIF=1.63)
  → Dropped religious3 (VIF=1.51)

Winner: None
No-multicollinearity variables: ['religious1', 'religious2', 'religious3', 'religious4']

======== Processing category: gender_attitudes ========

🌟 Processing group with 6 variables: ['ga_leaders_male_better', 'ga_edu_male_priority', 'ga_exec_male_better', 'ga_jobs_male_priority', 'ga_income_woman_problem', 'ga_women_less_corrupt']

VIF loop (ga):  17%|█▋        | 1/6 [00:00<00:01,  4.77it/s]

  → Added ga_exec_male_better (VIF=13.96)

  → Added ga_leaders_male_better (VIF=10.21)
  → Dropped ga_jobs_male_priority (VIF=7.41)
  → Dropped ga_income_woman_problem (VIF=7.00)
  → Dropped ga_edu_male_priority (VIF=6.87)
  → Dropped ga_women_less_corrupt (VIF=3.75)

Winner: ga_leaders_male_better (|corr| = 0.0058)
Survivors (high-VIF): ['ga_exec_male_better', 'ga_leaders_male_better']

Final inter-VIF winners: {'belonging': 'belonging1', 'esteem': 'esteem3', 'safety': 'safety5', 'physio': 'physio1', 'civic': 'civic53', 'trust': 'trust3', 'growth': 'growth16', 'ethical': 'ethical80', 'compassion': None, 'education': 'dad_education_level', 'socioeconomic': None, 'immigrant': None, 'religious': None, 'gender_attitudes': 'ga_leaders_male_better'}

In [ ]:
inter_grp_kept = [var for var in winner_grp_var.values() if var is not None]

non_mul_corr_grp_vars = [item for sublist in non_multi_corr_grp_vars.values() for item in sublist]
intra_vars = non_mul_corr_grp_vars + inter_grp_kept + non_grp_vars # combine the winner with ungrouped variables for intra-VIF

print(intra_vars)

['compassion1', 'compassion2', 'compassion3', 'compassion4', 'chief_wage', 'social_class', 'income_scale', 'immigrant', 'mom_immigrant', 'dad_immigrant', 'religious1', 'religious2', 'religious3', 'religious4', 'belonging1', 'esteem3', 'safety5', 'physio1', 'civic53', 'trust3', 'growth16', 'ethical80', 'dad_education_level', 'ga_leaders_male_better', 'age', 'citizenship', 'comp_good_vs_harm', 'emp_prior_immig', 'gov_vs_individual', 'income_eq_vs_diff', 'l_vs_r_political', 'live_with_parent', 'marital_status', 'num_of_child', 'num_of_household', 'pri_vs_state', 'sact', 'sex']

In [ ]:
intra_cols_kept, dropped =intra_vif(df_imputed, intra_vars, threshold=10)

🌟 Processing intra-VIF for 38 variables: ['compassion1', 'compassion2', 'compassion3', 'compassion4', 'chief_wage', 'social_class', 'income_scale', 'immigrant', 'mom_immigrant', 'dad_immigrant', 'religious1', 'religious2', 'religious3', 'religious4', 'belonging1', 'esteem3', 'safety5', 'physio1', 'civic53', 'trust3', 'growth16', 'ethical80', 'dad_education_level', 'ga_leaders_male_better', 'age', 'citizenship', 'comp_good_vs_harm', 'emp_prior_immig', 'gov_vs_individual', 'income_eq_vs_diff', 'l_vs_r_political', 'live_with_parent', 'marital_status', 'num_of_child', 'num_of_household', 'pri_vs_state', 'sact', 'sex']

Intra-VIF loop:   3%|▎         | 1/38 [00:10<06:17, 10.19s/it]

  → Dropped belonging1 (VIF=96.43)

Intra-VIF loop:   5%|▌         | 2/38 [00:18<05:26,  9.08s/it]

  → Dropped citizenship (VIF=47.83)

Intra-VIF loop:   8%|▊         | 3/38 [00:25<04:45,  8.16s/it]

  → Dropped trust3 (VIF=41.72)

Intra-VIF loop:  11%|█         | 4/38 [00:33<04:29,  7.94s/it]

  → Dropped civic53 (VIF=25.59)

Intra-VIF loop:  13%|█▎        | 5/38 [00:40<04:20,  7.89s/it]

  → Dropped esteem3 (VIF=24.24)

Intra-VIF loop:  16%|█▌        | 6/38 [00:48<04:06,  7.70s/it]

  → Dropped growth16 (VIF=22.68)

Intra-VIF loop:  18%|█▊        | 7/38 [00:56<03:58,  7.71s/it]

  → Dropped physio1 (VIF=21.54)

Intra-VIF loop:  21%|██        | 8/38 [01:01<03:34,  7.14s/it]

  → Dropped safety5 (VIF=15.49)

Intra-VIF loop:  24%|██▎       | 9/38 [01:07<03:11,  6.60s/it]

  → Dropped sact (VIF=14.04)

Intra-VIF loop:  26%|██▋       | 10/38 [01:11<02:47,  5.99s/it]

  → Dropped social_class (VIF=12.68)

Intra-VIF loop:  29%|██▉       | 11/38 [01:19<02:51,  6.35s/it]

  → Dropped emp_prior_immig (VIF=12.41)

Intra-VIF loop:  32%|███▏      | 12/38 [01:24<02:39,  6.15s/it]

  → Dropped ethical80 (VIF=11.15)

Intra-VIF loop:  34%|███▍      | 13/38 [01:29<02:20,  5.64s/it]

  → Dropped l_vs_r_political (VIF=10.72)

Remaining variables after intra-VIF: ['compassion1', 'compassion2', 'compassion3', 'compassion4', 'chief_wage', 'income_scale', 'immigrant', 'mom_immigrant', 'dad_immigrant', 'religious1', 'religious2', 'religious3', 'religious4', 'dad_education_level', 'ga_leaders_male_better', 'age', 'comp_good_vs_harm', 'gov_vs_individual', 'income_eq_vs_diff', 'live_with_parent', 'marital_status', 'num_of_child', 'num_of_household', 'pri_vs_state', 'sex']

In [ ]:
final_cols = []
for c in intra_cols_kept + inter_grp_kept + ['sact']: # preserve sact
    if c not in final_cols:
        final_cols.append(c)

cat_cols = df_fea_eng.select_dtypes(include='category').columns.to_list()
final_cols = final_cols + cat_cols + [target] # happy
print(final_cols)

['compassion1', 'compassion2', 'compassion3', 'compassion4', 'chief_wage', 'income_scale', 'immigrant', 'mom_immigrant', 'dad_immigrant', 'religious1', 'religious2', 'religious3', 'religious4', 'dad_education_level', 'ga_leaders_male_better', 'age', 'comp_good_vs_harm', 'gov_vs_individual', 'income_eq_vs_diff', 'live_with_parent', 'marital_status', 'num_of_child', 'num_of_household', 'pri_vs_state', 'sex', 'belonging1', 'esteem3', 'safety5', 'physio1', 'civic53', 'trust3', 'growth16', 'ethical80', 'sact', 'society_concern', 'protect_env_vs_econ', 'immig_policy_prefer', 'freedom_eq', 'freedom_sec', 'country_aim1', 'country_aim2', 'respon_aim1', 'respon_aim2', 'important_choice1', 'important_choice2', 'employment_status', 'occupational_group', 'dad_occupational_group', 'Employment_sector', 'family_saving', 'religiosity', 'happy']

Keep only the final selected variables from VIF.

In [ ]:
df_fea_eng = df_fea_eng[final_cols]
df_fea_eng.head()

,compassion1,compassion2,compassion3,compassion4,chief_wage,income_scale,immigrant,mom_immigrant,dad_immigrant,religious1,religious2,religious3,religious4,dad_education_level,ga_leaders_male_better,age,comp_good_vs_harm,gov_vs_individual,income_eq_vs_diff,live_with_parent,marital_status,num_of_child,num_of_household,pri_vs_state,sex,belonging1,esteem3,safety5,physio1,civic53,trust3,growth16,ethical80,sact,society_concern,protect_env_vs_econ,immig_policy_prefer,freedom_eq,freedom_sec,country_aim1,country_aim2,respon_aim1,respon_aim2,important_choice1,important_choice2,employment_status,occupational_group,dad_occupational_group,Employment_sector,family_saving,religiosity,happy
0,1,0,2,2,1,3,0,0,0,<NA>,1,0,0,1,2,61,3,1,1,0,1,2,2,3,0,4,4,1,2,4,4,4,1,4,2,2,1,2,2,1,3,3,4,1,3,1,6,9,1,2,3,3
1,1,0,2,2,0,3,0,0,0,4,1,1,<NA>,1,<NA>,61,3,1,3,0,1,2,4,5,1,4,4,2,4,4,4,4,3,4,NaN,1,2,1,2,1,2,3,1,1,4,1,8,10,2,2,3,4
2,3,<NA>,<NA>,2,0,2,1,1,1,<NA>,1,1,1,4,1,42,3,1,3,0,1,4,6,3,1,4,4,2,5,3,4,4,2,5,2,NaN,2,2,2,1,2,3,4,4,1,5,0,6,NaN,2,3,3
3,2,0,2,2,0,3,0,0,0,3,1,0,<NA>,2,2,64,3,3,1,0,1,2,2,3,1,4,4,2,3,4,4,4,<NA>,3,NaN,1,2,2,1,2,1,1,2,1,4,1,8,9,2,2,3,3
4,4,2,<NA>,2,0,2,1,1,1,<NA>,1,0,0,2,<NA>,52,5,1,1,0,0,3,8,3,1,4,3,3,3,5,4,3,3,3,2,2,3,2,2,1,4,3,1,1,4,1,8,9,2,2,3,2

In [ ]:
df_fea_eng.shape

(95528, 52)

Check the variables with high missing percentage ( >15% may cause bias for nominal).

In [ ]:
na_cols_results = get_na_cols_perc(df_fea_eng,threshold=0.1)

dad_education_level : 0.14240850850012562
dad_occupational_group : 0.13609622309689307
Employment_sector : 0.2406414873126204
----------------------------------------------------------------------------------------------------
Total column:  3

#### Target Variable Cleaning
Removing rows with missing target values.

In [ ]:
# Step 1: drop NA rows found in target
target = 'happy'
df_fea_eng = df_fea_eng[~df_fea_eng[target].isna()]

df_fea_eng.shape

(94883, 52)

#### Feature Type & Missing Value Preparation
Change ordinal and numerical variables data type to support imputation

In [ ]:
df_fea_eng.dtypes

compassion1                  Int64
compassion2                  Int64
compassion3                  Int64
compassion4                  Int64
chief_wage                   Int64
income_scale                 Int64
immigrant                    Int64
mom_immigrant                Int64
dad_immigrant                Int64
religious1                   Int64
religious2                   Int64
religious3                   Int64
religious4                   Int64
dad_education_level          Int64
ga_leaders_male_better       Int64
age                          Int64
comp_good_vs_harm            Int64
gov_vs_individual            Int64
income_eq_vs_diff            Int64
live_with_parent             Int64
marital_status               Int64
num_of_child                 Int64
num_of_household             Int64
pri_vs_state                 Int64
sex                          Int64
belonging1                   Int64
esteem3                      Int64
safety5                      Int64
physio1                      Int64
civic53                      Int64
trust3                       Int64
growth16                     Int64
ethical80                    Int64
sact                         Int64
society_concern           category
protect_env_vs_econ       category
immig_policy_prefer       category
freedom_eq                category
freedom_sec               category
country_aim1              category
country_aim2              category
respon_aim1               category
respon_aim2               category
important_choice1         category
important_choice2         category
employment_status         category
occupational_group        category
dad_occupational_group    category
Employment_sector         category
family_saving             category
religiosity               category
happy                        Int64
dtype: object

In [ ]:
ord_num_cols = df_fea_eng.select_dtypes(exclude='category').columns

# convert those ordinal and numerical variables into float first so that NA can be replaced
df_fea_eng[ord_num_cols] = df_fea_eng[ord_num_cols].astype("float")

# convert into numpy nan for iterative imputing
df_fea_eng[ord_num_cols] = df_fea_eng[ord_num_cols].replace({pd.NA : np.nan})

Convert both numerical and categorical variables data from pd.NA to np.nan for imputation.

In [ ]:
# category will store NaN as <NA> implicitly
cat_cols = df_fea_eng.select_dtypes(include='category').columns

for col in cat_cols:
    # change to object to hold numpy nan
    df_fea_eng[col] = df_fea_eng[col].astype(object).where(df_fea_eng[col].notna(), np.nan)

In [ ]:
df_fea_eng.dtypes

compassion1               float64
compassion2               float64
compassion3               float64
compassion4               float64
chief_wage                float64
income_scale              float64
immigrant                 float64
mom_immigrant             float64
dad_immigrant             float64
religious1                float64
religious2                float64
religious3                float64
religious4                float64
dad_education_level       float64
ga_leaders_male_better    float64
age                       float64
comp_good_vs_harm         float64
gov_vs_individual         float64
income_eq_vs_diff         float64
live_with_parent          float64
marital_status            float64
num_of_child              float64
num_of_household          float64
pri_vs_state              float64
sex                       float64
belonging1                float64
esteem3                   float64
safety5                   float64
physio1                   float64
civic53                   float64
trust3                    float64
growth16                  float64
ethical80                 float64
sact                      float64
society_concern            object
protect_env_vs_econ        object
immig_policy_prefer        object
freedom_eq                 object
freedom_sec                object
country_aim1               object
country_aim2               object
respon_aim1                object
respon_aim2                object
important_choice1          object
important_choice2          object
employment_status          object
occupational_group         object
dad_occupational_group     object
Employment_sector          object
family_saving              object
religiosity                object
happy                     float64
dtype: object

Save data types.

In [ ]:
dtypes_dict = df_fea_eng.dtypes.apply(lambda x: x.name).to_dict()
with open(f'{DRIVE_DATA_PATH}/data/processed/data_types.json', 'w') as f:
    json.dump(dtypes_dict, f)

Export feature engineered data.

In [ ]:
df_fea_eng.to_csv(f'{DRIVE_DATA_PATH}/data/processed/df_fea_eng.csv', index=False)

Load feature engineered data.

In [14]:
# Load column types
with open(f'{DRIVE_DATA_PATH}/data/processed/data_types.json', 'r') as f:
    dtypes_dict = json.load(f)

# Read CSV with types
df_fea_eng = pd.read_csv(f'{DRIVE_DATA_PATH}/data/processed/df_fea_eng.csv', dtype=dtypes_dict)

#### Data Splitting

In [ ]:
target = 'happy'

X = df_fea_eng.drop(target, axis=1)
y = df_fea_eng[target]

In [ ]:
# Step 2: train/test/val split (stratified) to correct balancing
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp
)

#### Imputation Preparation

Set up imputation pipelines for categorical and numerical data.

In [ ]:
# ---------------------------
# Column groups: ordinal, nominal, discrete, continuous
# ---------------------------
continuous_cols = ['age'] # continuous
discrete_cols = [ c for c in X.columns          # discrete variables
    if X[c].nunique() >= 10 and X[c].dtype != 'object' and c not in continuous_cols]
ordinal_cols = [ c for c in X.columns           # ordinal variables
    if X[c].dropna().nunique() <= 10 and X[c].dtype != 'object'
]
nominal_cols = list(X.select_dtypes(include='object').columns) # nominal variables

print("Continuous: ",continuous_cols)
print("Discrete: ", discrete_cols)
print("Ordinal: ", ordinal_cols)
print("Nominal: ", nominal_cols)

Continuous:  ['age']
Discrete:  ['num_of_child', 'num_of_household']
Ordinal:  ['compassion1', 'compassion2', 'compassion3', 'compassion4', 'chief_wage', 'income_scale', 'immigrant', 'mom_immigrant', 'dad_immigrant', 'religious1', 'religious2', 'religious3', 'religious4', 'dad_education_level', 'ga_leaders_male_better', 'comp_good_vs_harm', 'gov_vs_individual', 'income_eq_vs_diff', 'live_with_parent', 'marital_status', 'pri_vs_state', 'sex', 'belonging1', 'esteem3', 'safety5', 'physio1', 'civic53', 'trust3', 'growth16', 'ethical80', 'sact']
Nominal:  ['society_concern', 'protect_env_vs_econ', 'immig_policy_prefer', 'freedom_eq', 'freedom_sec', 'country_aim1', 'country_aim2', 'respon_aim1', 'respon_aim2', 'important_choice1', 'important_choice2', 'employment_status', 'occupational_group', 'dad_occupational_group', 'Employment_sector', 'family_saving', 'religiosity']

Rounding and clipping functions to ensure imputed values are in valid range.

In [ ]:
def round_and_clip_array(X, columns, ranges, do_round=True):
    # Wrap as DataFrame
    df = pd.DataFrame(X, columns=columns)
    for col in columns:
        min_val, max_val = ranges[col]
        if do_round:
            df[col] = df[col].round()
        df[col] = df[col].clip(min_val, max_val) # ensure no out-of-scale data
    return df.values

def round_discrete(X, cols):
    df = pd.DataFrame(X, columns=cols)
    for col in cols:
        df[col] = df[col].round().clip(lower=0)  # ensures no negative counts
    return df.values

In [ ]:
# find the min max values for ordinal
ordinal_ranges = {
    col: (X_train[col].min(), X_train[col].max())
    for col in ordinal_cols
}

continuous_ranges = {
    col: ((X_train[col].min(), X_train[col].max()))
    for col in continuous_cols
}

# ordinal round and clip
ordinal_clip_transformer = FunctionTransformer(
    func=lambda X: round_and_clip_array(X, ordinal_cols, ordinal_ranges, do_round=True)
)

# discrete round
discrete_round_transformer = FunctionTransformer(
    func=lambda X: round_discrete(X, discrete_cols)
)

# continuous clip
continuous_clip_transformer = FunctionTransformer(
    func=lambda X: round_and_clip_array(X, continuous_cols, continuous_ranges, do_round=False)
)

Imputation pipelines.

In [ ]:
ordinal_pipeline = Pipeline([
    ("imputer", IterativeImputer(random_state=42)),
    ("round_clip", ordinal_clip_transformer)
])

continuous_pipeline = Pipeline([
    ("imputer", IterativeImputer(random_state=42)),
    ("clip", continuous_clip_transformer),
    ("scaler", StandardScaler())
])

discrete_pipeline = Pipeline([
    ("imputer", IterativeImputer(random_state=42)),
    ("round_discrete", discrete_round_transformer)
])

nominal_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

preprocessor = ColumnTransformer([
    ("ordinal", ordinal_pipeline, ordinal_cols),
    ("continuous", continuous_pipeline, continuous_cols),
    ("discrete", discrete_pipeline, discrete_cols),
    ("nominal", nominal_pipeline, nominal_cols)
])

#### Label Encode Target

Ensure the target variable (happy) starts from 0 for easier readiness in further evaluation.

In [ ]:
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_train = pd.DataFrame(y_train, columns=["happy"])

y_test = label_encoder.transform(y_test)
y_test = pd.DataFrame(y_test, columns=["happy"])

y_val = label_encoder.transform(y_val)
y_val = pd.DataFrame(y_val, columns=["happy"])

### RFECV

In [ ]:
# IMPORTANT: enable pandas output so RFECV receives column names
preprocessor.set_output(transform="pandas")

ColumnTransformer(transformers=[('ordinal',
                                 Pipeline(steps=[('imputer',
                                                  IterativeImputer(random_state=42)),
                                                 ('round_clip',
                                                  FunctionTransformer(func=<function <lambda> at 0x7e11d8e27240>))]),
                                 ['compassion1', 'compassion2', 'compassion3',
                                  'compassion4', 'chief_wage', 'income_scale',
                                  'immigrant', 'mom_immigrant', 'dad_immigrant',
                                  'religious1', 'religious2', 'religious3'...
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['society_concern', 'protect_env_vs_econ',
                                  'immig_policy_prefer', 'freedom_eq',
                                  'freedom_sec', 'country_aim1', 'country_aim2',
                                  'respon_aim1', 'respon_aim2',
                                  'important_choice1', 'important_choice2',
                                  'employment_status', 'occupational_group',
                                  'dad_occupational_group', 'Employment_sector',
                                  'family_saving', 'religiosity'])])

Run RFECV with the preprocessor using pipeline to avoid data leakage.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFECV

rfecv = RFECV(
    estimator=RandomForestClassifier(random_state=42),
    step=1,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

rfecv_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("selector", rfecv)
])

In [ ]:
y_train_1d = y_train.values.ravel() # use ravel to avoid DataConversionWarning
rfecv_pipeline.fit(X_train, y_train_1d)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('ordinal',
                                                  Pipeline(steps=[('imputer',
                                                                   IterativeImputer(random_state=42)),
                                                                  ('round_clip',
                                                                   FunctionTransformer(func=<function <lambda> at 0x7e11d8e27240>))]),
                                                  ['compassion1', 'compassion2',
                                                   'compassion3', 'compassion4',
                                                   'chief_wage', 'income_scale',
                                                   'immigrant', 'mom_immigrant',
                                                   'dad_immigrant',
                                                   'relig...
                                                   'freedom_eq', 'freedom_sec',
                                                   'country_aim1',
                                                   'country_aim2',
                                                   'respon_aim1', 'respon_aim2',
                                                   'important_choice1',
                                                   'important_choice2',
                                                   'employment_status',
                                                   'occupational_group',
                                                   'dad_occupational_group',
                                                   'Employment_sector',
                                                   'family_saving',
                                                   'religiosity'])])),
                ('selector',
                 RFECV(cv=5, estimator=RandomForestClassifier(random_state=42),
                       n_jobs=-1, scoring='accuracy'))])

In [ ]:
import numpy as np

selector = rfecv_pipeline.named_steps["selector"]
pre = rfecv_pipeline.named_steps["preprocessor"]

all_feature_names = []

for name, trans, cols in pre.transformers_:
    # Case 1: transformer is a Pipeline
    if hasattr(trans, "named_steps"):
        last_step = trans.named_steps[next(reversed(trans.named_steps))]
        if hasattr(last_step, "get_feature_names_out"):
            names = last_step.get_feature_names_out(cols)
        else:
            names = cols
    # Case 2: direct transformer with names (e.g., OneHotEncoder)
    elif hasattr(trans, "get_feature_names_out"):
        names = trans.get_feature_names_out(cols)
    # Case 3: no feature name support → fallback to original column names
    else:
        names = cols

    all_feature_names.extend(names)

all_feature_names = np.array(all_feature_names)

# Now apply RFECV mask
selected_features = all_feature_names[selector.support_]

print("Optimal number of features:", selector.n_features_)
print("Selected features:", list(selected_features))

Optimal number of features: 69
Selected features: [np.str_('compassion1'), np.str_('compassion2'), np.str_('compassion3'), np.str_('compassion4'), np.str_('chief_wage'), np.str_('income_scale'), np.str_('religious1'), np.str_('religious2'), np.str_('religious3'), np.str_('religious4'), np.str_('dad_education_level'), np.str_('ga_leaders_male_better'), np.str_('comp_good_vs_harm'), np.str_('gov_vs_individual'), np.str_('income_eq_vs_diff'), np.str_('live_with_parent'), np.str_('marital_status'), np.str_('pri_vs_state'), np.str_('sex'), np.str_('esteem3'), np.str_('safety5'), np.str_('physio1'), np.str_('civic53'), np.str_('trust3'), np.str_('growth16'), np.str_('ethical80'), np.str_('sact'), np.str_('age'), np.str_('num_of_child'), np.str_('num_of_household'), np.str_('society_concern_1'), np.str_('society_concern_2'), np.str_('protect_env_vs_econ_1'), np.str_('protect_env_vs_econ_2'), np.str_('immig_policy_prefer_2'), np.str_('immig_policy_prefer_3'), np.str_('freedom_eq_1'), np.str_('freedom_eq_2'), np.str_('freedom_sec_1'), np.str_('freedom_sec_2'), np.str_('country_aim1_1'), np.str_('country_aim1_2'), np.str_('country_aim1_3'), np.str_('country_aim2_1'), np.str_('country_aim2_2'), np.str_('country_aim2_3'), np.str_('country_aim2_4'), np.str_('respon_aim1_1'), np.str_('respon_aim1_2'), np.str_('respon_aim1_3'), np.str_('respon_aim2_1'), np.str_('respon_aim2_2'), np.str_('respon_aim2_3'), np.str_('respon_aim2_4'), np.str_('important_choice1_1'), np.str_('important_choice1_2'), np.str_('important_choice2_1'), np.str_('important_choice2_2'), np.str_('important_choice2_3'), np.str_('important_choice2_4'), np.str_('employment_status_1'), np.str_('occupational_group_1'), np.str_('dad_occupational_group_9'), np.str_('Employment_sector_1'), np.str_('Employment_sector_2'), np.str_('family_saving_1'), np.str_('family_saving_2'), np.str_('religiosity_1'), np.str_('religiosity_5')]

In [ ]:
# Transform the original DataFrames
X_train_transformed = rfecv_pipeline.named_steps["preprocessor"].transform(X_train)
X_val_transformed   = rfecv_pipeline.named_steps["preprocessor"].transform(X_val)
X_test_transformed  = rfecv_pipeline.named_steps["preprocessor"].transform(X_test)

# Ensure the transformed outputs are NumPy arrays
X_train_transformed = np.array(X_train_transformed)
X_val_transformed   = np.array(X_val_transformed)
X_test_transformed  = np.array(X_test_transformed)

In [ ]:
# selector is RFECV selector
selector = rfecv_pipeline.named_steps["selector"]

# convert to dataframe
X_train_final = pd.DataFrame(
    X_train_transformed[:, selector.support_],
    columns=selected_features
)
X_val_final = pd.DataFrame(
    X_val_transformed[:, selector.support_],
    columns=selected_features
)
X_test_final = pd.DataFrame(
    X_test_transformed[:, selector.support_],
    columns=selected_features
)

In [ ]:
# Retrieve columns which are filtered by RFECV
excluded_mask = ~selector.support_

# convert to dataframe
X_train_exc = pd.DataFrame(
    X_train_transformed[:, excluded_mask]
)
X_test_exc = pd.DataFrame(
    X_test_transformed[:, excluded_mask]
)
X_val_exc = pd.DataFrame(
    X_val_transformed[:, excluded_mask]
)


excluded_features = np.array(all_feature_names)[excluded_mask]

X_train_exc.columns = excluded_features
X_val_exc.columns = excluded_features
X_test_exc.columns = excluded_features

In [ ]:
# Export final X train ,test and validation sets with the belonging1

X_train_final = pd.concat(
    [X_train_exc['belonging1'], X_train_final],
    axis=1
)

X_test_final = pd.concat(
    [X_test_exc['belonging1'], X_test_final],
    axis=1
)

X_val_final = pd.concat(
    [X_val_exc['belonging1'], X_val_final],
    axis=1
)

X_train_final.to_csv(f'{DRIVE_DATA_PATH}/data/train_sets/X_train_final_ori.csv', index=False)
X_test_final.to_csv(f'{DRIVE_DATA_PATH}/data/test_sets/X_test_final.csv', index=False)
X_val_final.to_csv(f'{DRIVE_DATA_PATH}/data/val_sets/X_val_final.csv', index=False)

In [15]:
X_train_final = pd.read_csv(f'{DRIVE_DATA_PATH}/data/train_sets/X_train_final_ori.csv')
X_test_final = pd.read_csv(f'{DRIVE_DATA_PATH}/data/test_sets/X_test_final.csv')
X_val_final = pd.read_csv(f'{DRIVE_DATA_PATH}/data/val_sets/X_val_final.csv')

#### Target Class Granularity Selection

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# --- Step 1: Define binning schemes (hierarchical, from 0-based) ---
binning_steps = {
    '4-class': {0:0, 1:1, 2:2, 3:3},  # original 4 classes
    '3-class': {0:0, 1:1, 2:2, 3:2},  # merge top two classes
    '2-class': {0:0, 1:0, 2:1, 3:1}   # binary: unhappy vs happy
}

# --- Step 2: Evaluation function ---
def evaluate_model(X_train, y_train, X_val, y_val, model):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_val)
    return accuracy_score(y_val, y_pred)

# --- Step 3: Evaluate sequentially and update labels ---
results = []
y_train_versions = {}
y_val_versions = {}
y_test_versions = {}

# Start with original y_train, y_val
y_train_base = y_train["happy"].copy()
y_val_base = y_val["happy"].copy()
y_test_base = y_test["happy"].copy()

for scheme_name in ['4-class', '3-class', '2-class']:
    bin_map = binning_steps[scheme_name]

    # Map train and val labels based on current labels (which update each iteration)
    y_train_binned = y_train_base.map(bin_map).astype(int)
    y_val_binned = y_val_base.map(bin_map).astype(int)
    y_test_binned = y_test_base.map(bin_map).astype(int)

    # Train and evaluate model
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    acc_val = evaluate_model(X_train_final, y_train_binned, X_val_final, y_val_binned, model)
    acc_test = evaluate_model(X_train_final, y_train_binned, X_test_final, y_test_binned, model)

    # Store results
    results.append({
        'Scheme': scheme_name,
        'Num_Classes': len(set(bin_map.values())),
        'Validation Accuracy': acc_val,
        'Test Accuracy': acc_test
    })

    # Store the binned versions after evaluation
    y_train_versions[scheme_name] = y_train_binned
    y_val_versions[scheme_name] = y_val_binned
    y_test_versions[scheme_name] = y_test_binned

    # Update base labels for next iteration
    y_train_base = y_train_binned
    y_val_base = y_val_binned
    y_test_base = y_test_binned

# Final: show sorted results
results_df = pd.DataFrame(results).sort_values('Validation Accuracy', ascending=False)
print(results_df)

    Scheme  Num_Classes  Validation Accuracy  Test Accuracy
2  2-class            2             0.876335       0.874868
1  3-class            3             0.867552       0.865454
0  4-class            4             0.639896       0.641959

In [ ]:
y_train_final = y_train_versions['2-class']
y_val_final = y_val_versions['2-class']
y_test_final = y_test_versions['2-class']

In [ ]:
# Export final y train ,test and validation sets
y_train_final.to_csv(f'{DRIVE_DATA_PATH}/data/train_sets/y_train_final_ori.csv', index=False)
y_test_final.to_csv(f'{DRIVE_DATA_PATH}/data/test_sets/y_test_final.csv', index=False)
y_val_final.to_csv(f'{DRIVE_DATA_PATH}/data/val_sets/y_val_final.csv', index=False)

In [16]:
y_train_final = pd.read_csv(f'{DRIVE_DATA_PATH}/data/train_sets/y_train_final_ori.csv')
y_test_final = pd.read_csv(f'{DRIVE_DATA_PATH}/data/test_sets/y_test_final.csv')
y_val_final = pd.read_csv(f'{DRIVE_DATA_PATH}/data/val_sets/y_val_final.csv')

#### SMOTE

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

def run_imbalance_experiment(
    sampler,
    X_train,
    y_train,
    X_val,
    y_val,
    X_test,
    y_test,
    model=None,
    name="method"
):
    """
    sampler: imblearn sampler object OR None
    """

    # Default model
    if model is None:
        model = RandomForestClassifier(random_state=42)

    # =========================
    # 1. Resampling step
    # =========================
    if sampler is None:
        X_res, y_res = X_train, y_train
    else:
        X_res, y_res = sampler.fit_resample(X_train, y_train)

    # =========================
    # 2. Train
    # =========================
    model.fit(X_res, y_res)

    # =========================
    # 3. Predict
    # =========================
    y_val_pred = model.predict(X_val)
    y_test_pred = model.predict(X_test)

    results = {
        "method": name,
        "X_resampled": X_res,
        "y_resampled": y_res,
        "y_val_pred": y_val_pred,
        "y_test_pred": y_test_pred,
        "val_accuracy": accuracy_score(y_val, y_val_pred),
        "test_accuracy": accuracy_score(y_test, y_test_pred)
    }

    print(f"\n=== {name} ===")
    print(f"Validation Accuracy: {results['val_accuracy']:.6f}")
    print(f"Test Accuracy: {results['test_accuracy']:.6f}")

    return results

In [ ]:
from imblearn.over_sampling import SMOTE, ADASYN
from imblearn.under_sampling import RandomUnderSampler

samplers = [
    (None, "No Resampling"),
    (SMOTE(random_state=42), "SMOTE"),
    (ADASYN(random_state=42), "ADASYN"),
    (RandomUnderSampler(random_state=42), "Undersampling")
]

results = []

for sampler, name in samplers:
    res = run_imbalance_experiment(
        sampler=sampler,
        X_train=X_train_final,
        y_train=y_train_final,
        X_val=X_val_final,
        y_val=y_val_final,
        X_test=X_test_final,
        y_test=y_test_final,
        name=name
    )
    results.append(res)

=== No Resampling ===
Validation Accuracy: 0.876335
Test Accuracy: 0.874868

=== SMOTE ===
Validation Accuracy: 0.876967
Test Accuracy: 0.876695

=== ADASYN ===
Validation Accuracy: 0.878021
Test Accuracy: 0.877889

=== Undersampling ===
Validation Accuracy: 0.759556
Test Accuracy: 0.752196

In [ ]:
from sklearn.metrics import classification_report

for res in results:
    print(f"\n=== {res['method']} ===")
    print(classification_report(y_test_final, res['y_test_pred'], digits=4))

=== No Resampling ===
              precision    recall  f1-score   support

           0     0.7048    0.2229    0.3387      2046
           1     0.8830    0.9843    0.9309     12187

    accuracy                         0.8749     14233
   macro avg     0.7939    0.6036    0.6348     14233
weighted avg     0.8574    0.8749    0.8458     14233


=== SMOTE ===
              precision    recall  f1-score   support

           0     0.6694    0.2810    0.3959      2046
           1     0.8900    0.9767    0.9313     12187

    accuracy                         0.8767     14233
   macro avg     0.7797    0.6289    0.6636     14233
weighted avg     0.8583    0.8767    0.8544     14233


=== ADASYN ===
              precision    recall  f1-score   support

           0     0.6906    0.2727    0.3910      2046
           1     0.8892    0.9795    0.9321     12187

    accuracy                         0.8779     14233
   macro avg     0.7899    0.6261    0.6616     14233
weighted avg     0.8606    0.8779    0.8544     14233


=== Undersampling ===
              precision    recall  f1-score   support

           0     0.3409    0.7757    0.4737      2046
           1     0.9521    0.7483    0.8380     12187

    accuracy                         0.7522     14233
   macro avg     0.6465    0.7620    0.6558     14233
weighted avg     0.8642    0.7522    0.7856     14233

Pick with SMOTE

In [ ]:
res_smote = results[1]
print(res_smote['method'])

X_train_final_smote = res_smote["X_resampled"]
y_train_final_smote = res_smote["y_resampled"]

X_train_final_smote.to_csv(f'{DRIVE_DATA_PATH}/data/train_sets/X_train_final_smote.csv', index=False)
y_train_final_smote.to_csv(f'{DRIVE_DATA_PATH}/data/train_sets/y_train_final_smote.csv', index=False)

SMOTE

In [ ]:
# res_adasyn = results[2]
# print(res_adasyn['method'])

# X_train_final_adasyn = res_adasyn["X_resampled"]
# y_train_final_adasyn = res_adasyn["y_resampled"]

# X_train_final_adasyn.to_csv(f'{DRIVE_DATA_PATH}/data/train_sets/X_train_final_adasyn.csv', index=False)
# y_train_final_adasyn.to_csv(f'{DRIVE_DATA_PATH}/data/train_sets/y_train_final_adasyn.csv', index=False)

ADASYN